In [1]:
# Importing Dependencies
import numpy as np
import gym
from gym.envs.box2d.car_racing import *
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPool2D, BatchNormalization
from keras.optimizers import Adam
from statistics import mean
from pyglet.window import key
import time
from tqdm import tqdm 
import os
from keras.utils import normalize

C:\Users\Piyush\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
# Function for generating data by playing
def start_playing(n_episodes):
    a = np.array( [0.0, 0.0, 0.0] )
    def key_press(k, mod):
        global restart
        if k==0xff0d: restart = True
        if k==key.LEFT:  a[0] = -1.0
        if k==key.RIGHT: a[0] = +1.0
        if k==key.UP:    a[1] = +1.0
        if k==key.DOWN:  a[2] = +0.8   
    def key_release(k, mod):
        if k==key.LEFT  and a[0]==-1.0: a[0] = 0
        if k==key.RIGHT and a[0]==+1.0: a[0] = 0
        if k==key.UP:    a[1] = 0
        if k==key.DOWN:  a[2] = 0
    
    env = CarRacing()
    env.render()
    env.viewer.window.on_key_press = key_press
    env.viewer.window.on_key_release = key_release
    
    for episode in range(n_episodes):
        prev_observation = env.reset()
        if episode==0:
            X = np.array(prev_observation.tolist())
            y = np.array([0.,0.,0.])
        restart = False
        while True:
            action = a
            observation, reward, done, info = env.step(action)
            X = np.vstack((X, prev_observation))
            y = np.vstack((y, action))
            prev_observation=observation
            env.render()
            if done or restart: break
        time.sleep(2)    
    np.save('train_X.npy', X)
    np.save('train_y.npy', y)    
    env.close()
    return X, y

In [3]:
# Playing the to create data
X, y=start_playing(20)

Track generation: 1121..1405 -> 284-tiles track
Track generation: 925..1162 -> 237-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1228..1538 -> 310-tiles track
Track generation: 1132..1419 -> 287-tiles track
Track generation: 1282..1607 -> 325-tiles track
Track generation: 1171..1472 -> 301-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1120..1404 -> 284-tiles track
Track generation: 1030..1291 -> 261-tiles track
Track generation: 1119..1403 -> 284-tiles track
Track generation: 1126..1412 -> 286-tiles track
Track generation: 1413..1770 -> 357-tiles track
Track generation: 1230..1541 -> 311-tiles track
Track generation: 1246..1562 -> 316-tiles track
Track generation: 1128..1414 -> 286-tiles track
Track generation: 1085..1365 -> 280-tiles track
Track generation: 1387..1738 -> 351-tiles track
Track generation: 992..1251 -> 259-tiles track
Track generation: 1029..1296 -> 267-tiles 

In [8]:
# Combining gameplay files
temp = np.load('train_data-549.4999999999591.npy')
tempX = [i[0] for i in temp]
tempy = [i[1] for i in temp]
X = np.array(tempX)
y = np.array(tempy)
for file in tqdm(os.listdir('Data/')):
    temp = np.load('Data/' + file)
    tempX = [i[0] for i in temp]
    tempy = [i[1] for i in temp]
    tempX = np.array(tempX)
    tempy = np.array(tempy)
    X  = np.concatenate([X, tempX], axis=0)
    y  = np.concatenate([y, tempy], axis=0)

np.save('X.npy', X)    

100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:05<00:00,  1.60it/s]


In [5]:
# Converting output to proper OneHot array
Y=[]
for i in range(len(y)):  
    if np.array_equal(y[i], np.array([0,1,0])):
        Y.append(np.array([0,0,1,0,0]))
    elif np.array_equal(y[i], np.array([0,0,0.8])):
        Y.append(np.array([0,0,0,1,0]))
    elif np.array_equal(y[i], np.array([1,0,0])):
        Y.append(np.array([0,1,0,0,0]))
    elif np.array_equal(y[i], np.array([-1,0,0])):
        Y.append(np.array([1,0,0,0,0]))
    else:
        Y.append(np.array([0,0,0,0,1]))      
      
np.save('y_modified.npy', Y)    

In [5]:
# Loading the data
X = np.load('train_X.npy')
y = np.load('y_modified.npy')
X = X.reshape(-1,96,96,3)
print(X.shape)
print(y.shape)

(20450, 96, 96, 3)
(20450, 5)


In [26]:
# Variation in generated data
left=np.array([1,0,0,0,0])
right=np.array([0,1,0,0,0])
straight=np.array([0,0,1,0,0])
stop=np.array([0,0,0,1,0])
no_key=np.array([0,0,0,0,1])
l=0
r=0
s=0
b=0
nk=0

for key in y:
    if np.array_equal(key, left):
        l+=1
    elif np.array_equal(key, right):
        r+=1
    elif np.array_equal(key, straight):
        s+=1
    elif np.array_equal(key, stop):
        b+=1
    elif np.array_equal(key, no_key):
        nk+=1    
      
print(l,r,s,b,nk)    

2694 1318 4443 179 11816


In [19]:
model = Sequential()

model.add(Conv2D(filters = 16, kernel_size = (5,5),padding = 'Same', 
                 activation ='relu', input_shape = (96,96,3)))
model.add(Conv2D(filters = 16, kernel_size = (5,5),padding = 'Same', 
                 activation ='relu'))
model.add(BatchNormalization())
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Dropout(0.5))

model.add(Conv2D(filters = 32, kernel_size = (3,3),padding = 'Same', 
                 activation ='relu'))
model.add(Conv2D(filters = 32, kernel_size = (3,3),padding = 'Same', 
                 activation ='relu'))
model.add(BatchNormalization())
model.add(MaxPool2D(pool_size=(2,2), strides=(2,2)))
model.add(Dropout(0.5))


model.add(Flatten())
model.add(Dense(256, activation = "relu"))
model.add(BatchNormalization())
model.add(Dropout(0.5))

model.add(Dense(5, activation = "softmax"))

In [20]:
optimizer = Adam(lr=0.0001)
model.compile(optimizer = optimizer, loss = "categorical_crossentropy")

In [21]:
model.fit(X, y, epochs=10, validation_split=0.2, batch_size=600, verbose=1, shuffle=True)

Train on 16360 samples, validate on 4090 samples
Epoch 1/10
16360/16360 [==============================] - ETA: 45s - loss: 2.78 - ETA: 25s - loss: 2.73 - ETA: 19s - loss: 2.68 - ETA: 15s - loss: 2.66 - ETA: 13s - loss: 2.62 - ETA: 11s - loss: 2.59 - ETA: 10s - loss: 2.54 - ETA: 9s - loss: 2.5119 - ETA: 8s - loss: 2.471 - ETA: 8s - loss: 2.457 - ETA: 7s - loss: 2.435 - ETA: 6s - loss: 2.411 - ETA: 6s - loss: 2.390 - ETA: 5s - loss: 2.372 - ETA: 5s - loss: 2.355 - ETA: 4s - loss: 2.352 - ETA: 4s - loss: 2.352 - ETA: 3s - loss: 2.337 - ETA: 3s - loss: 2.319 - ETA: 2s - loss: 2.314 - ETA: 2s - loss: 2.296 - ETA: 2s - loss: 2.287 - ETA: 1s - loss: 2.276 - ETA: 1s - loss: 2.268 - ETA: 0s - loss: 2.267 - ETA: 0s - loss: 2.256 - ETA: 0s - loss: 2.254 - 12s 708us/step - loss: 2.2528 - val_loss: 1.2970
Epoch 2/10
16360/16360 [==============================] - ETA: 8s - loss: 2.045 - ETA: 8s - loss: 2.007 - ETA: 8s - loss: 2.014 - ETA: 7s - loss: 2.012 - ETA: 7s - loss: 2.015 - ETA: 7s - loss: 2

In [27]:
# Saving the Model
model.save('Models/first_modelv0')

In [ ]:
# Loading the Model
model.load('Models/first-model')

In [25]:
#scores = []
#choices = []
env = CarRacing()
for each_game in range(3):
    #score = 0
    #game_memory = []
    prev_obs = env.reset()
    for i in range(1000):
        env.render()
        out = model.predict(prev_obs.reshape(-1,96,96,3))[0]
        print(out)
        
        if out[0]<=0.45:
            out[0]=0  
        if out[1]<=0.2:
            out[1]=0
        if out[2]<=0.01:
            out[2]=0   
        if out[3]<=0.47:
            out[3]=0
        if out[4]<=9:
            out[4]=0    
        
        output = np.argmax(out)
        action = np.zeros(5)
        np.put(action, output, 1)
        #choices.append(action)
        if np.array_equal(action, np.array([0,0,1,0,0])):
            action=np.array([0,1,0])
        elif np.array_equal(action, np.array([0,0,0,1,0])):
            action=np.array([0,0,0.8])
        elif np.array_equal(action, np.array([0,1,0,0,0])):
            action=np.array([1,0,0])
        elif np.array_equal(action, np.array([1,0,0,0,0])):
            action=np.array([-1,0,0])
        else:
            action=np.array([0,0,0,0,0])
        
        new_observation, reward, done, info = env.step(action)
        print(action,"by nn")
        prev_obs = new_observation
        #game_memory.append([new_observation, action])
        #score+=reward
        if done: 
            break
    #scores.append(score)
    #print('Episode {} Score: {}'.format(each_game+1,score))
    env.close()
#print('Average Score:',sum(scores)/len(scores))

Track generation: 1101..1380 -> 279-tiles track
[4.7221249e-05 1.9628758e-04 1.5701357e-10 3.5686833e-03 9.9618787e-01]
[-1  0  0] by nn
[3.1089790e-19 1.2077008e-12 8.5848971e-24 1.5339471e-09 1.0000000e+00]
[-1  0  0] by nn
[1.0862435e-21 5.5307684e-14 9.2980333e-25 8.6731575e-07 9.9999917e-01]
[-1  0  0] by nn
[1.8810872e-10 3.9375454e-08 1.2517567e-12 1.2999316e-08 1.0000000e+00]
[-1  0  0] by nn
[7.3507184e-01 9.1152065e-02 1.5107028e-05 1.6647963e-01 7.2813691e-03]
[-1  0  0] by nn
[8.3602285e-01 4.5435719e-02 2.1362997e-05 1.1798692e-01 5.3307001e-04]
[-1  0  0] by nn
[9.6824932e-01 8.7599205e-03 7.9003312e-06 2.2968993e-02 1.3818704e-05]
[-1  0  0] by nn
[9.9396849e-01 9.5307000e-04 1.9674803e-07 5.0782389e-03 2.3777117e-08]
[-1  0  0] by nn
[9.9603146e-01 5.4239994e-04 2.3023529e-07 3.4259257e-03 4.0482437e-08]
[-1  0  0] by nn
[9.9490285e-01 1.0684681e-03 1.1498599e-06 4.0268153e-03 7.3183082e-07]
[-1  0  0] by nn
[9.8896605e-01 3.2656207e-03 7.7227232e-06 7.7370075e-03 2.354

[0.814459   0.10722415 0.01195067 0.06448615 0.00187995]
[-1  0  0] by nn
[0.8286083  0.10116516 0.01286161 0.05223804 0.00512694]
[-1  0  0] by nn
[0.81920767 0.10290135 0.01404934 0.05220523 0.01163647]
[-1  0  0] by nn
[0.815993   0.08034269 0.01995308 0.05019597 0.03351539]
[-1  0  0] by nn
[0.81071776 0.05810343 0.02001009 0.04686131 0.06430732]
[-1  0  0] by nn
[0.8236493  0.04067479 0.014635   0.03879822 0.08224273]
[-1  0  0] by nn
[0.83092636 0.03310649 0.01262354 0.03341248 0.08993114]
[-1  0  0] by nn
[0.83204997 0.03205341 0.0111258  0.03155968 0.09321108]
[-1  0  0] by nn
[0.83307004 0.02868696 0.01014186 0.03233327 0.09576783]
[-1  0  0] by nn
[0.8144788  0.03246695 0.01103737 0.03224618 0.1097706 ]
[-1  0  0] by nn
[0.8089731  0.03061273 0.01299056 0.04076448 0.10665926]
[-1  0  0] by nn
[0.8050322  0.03070541 0.01238961 0.0415264  0.11034638]
[-1  0  0] by nn
[0.80003023 0.03320189 0.01654265 0.04329813 0.10692716]
[-1  0  0] by nn
[0.7660308  0.04789697 0.02383314 0.04

[0.12858744 0.56346345 0.01818814 0.03719619 0.25256473]
[1 0 0] by nn
[0.14237753 0.50044054 0.02787422 0.03825463 0.29105318]
[1 0 0] by nn
[0.16196828 0.41810802 0.05164701 0.04620298 0.32207373]
[1 0 0] by nn
[0.19977918 0.31756777 0.08469459 0.05216914 0.3457893 ]
[1 0 0] by nn
[0.2559337  0.20350185 0.12132747 0.06523915 0.35399774]
[1 0 0] by nn
[0.36112425 0.13621014 0.11211437 0.06869925 0.32185203]
[0 1 0] by nn
[0.5052536  0.09363912 0.06631509 0.06137509 0.2734171 ]
[-1  0  0] by nn
[0.6567606  0.0577898  0.02571411 0.03805623 0.22167926]
[-1  0  0] by nn
[0.7486293  0.03918315 0.01177627 0.02730441 0.17310685]
[-1  0  0] by nn
[0.82010806 0.03052316 0.00551907 0.02062709 0.12322268]
[-1  0  0] by nn
[0.85711974 0.02714646 0.00352758 0.01716839 0.09503778]
[-1  0  0] by nn
[0.86828095 0.02904837 0.00346455 0.01783893 0.08136715]
[-1  0  0] by nn
[0.86378765 0.03123447 0.00466946 0.0235577  0.07675073]
[-1  0  0] by nn
[0.88758564 0.02688634 0.00316127 0.02116757 0.06119915]

[0.19857012 0.5502702  0.00358895 0.03328585 0.21428496]
[1 0 0] by nn
[0.18472244 0.55365664 0.00403564 0.03600624 0.22157899]
[1 0 0] by nn
[0.24425125 0.46531233 0.00459558 0.03418555 0.25165522]
[1 0 0] by nn
[0.22631833 0.43932864 0.00624693 0.03367531 0.29443088]
[1 0 0] by nn
[0.2211756  0.4516808  0.00927234 0.03476507 0.2831062 ]
[1 0 0] by nn
[0.2543062  0.34208632 0.01270108 0.04100923 0.34989712]
[1 0 0] by nn
[0.28482157 0.24093547 0.02186981 0.05385841 0.39851475]
[1 0 0] by nn
[0.3628696  0.15328309 0.02734457 0.06232516 0.39417762]
[0 1 0] by nn
[0.43569717 0.10396111 0.02388483 0.06826797 0.3681889 ]
[0 1 0] by nn
[0.53446716 0.08365627 0.01970308 0.07041021 0.29176325]
[-1  0  0] by nn
[0.5516571  0.05705618 0.02001642 0.0714623  0.29980794]
[-1  0  0] by nn
[0.66359997 0.05153583 0.0076029  0.04330922 0.23395206]
[-1  0  0] by nn
[0.67960244 0.06345727 0.00568239 0.04826938 0.20298846]
[-1  0  0] by nn
[0.7140882  0.06365517 0.00526756 0.04573454 0.17125456]
[-1  0  

[0.67740977 0.04425943 0.02058094 0.03598372 0.22176617]
[-1  0  0] by nn
[0.6506965  0.05302519 0.02124099 0.03234839 0.24268895]
[-1  0  0] by nn
[0.62071335 0.06062797 0.02992606 0.04152662 0.24720599]
[-1  0  0] by nn
[0.525434   0.11611973 0.04415837 0.05151073 0.2627772 ]
[-1  0  0] by nn
[0.44954708 0.18175285 0.05578717 0.05557609 0.25733683]
[0 1 0] by nn
[0.29146186 0.2833695  0.06131564 0.04589039 0.3179626 ]
[1 0 0] by nn
[0.20006792 0.3413027  0.056991   0.03938206 0.36225632]
[1 0 0] by nn
[0.2010184  0.3551092  0.04029961 0.033055   0.3705178 ]
[1 0 0] by nn
[0.18802348 0.39818618 0.03601634 0.03331189 0.34446213]
[1 0 0] by nn
[0.19167313 0.40745425 0.03401422 0.03720679 0.3296516 ]
[1 0 0] by nn
[0.17225835 0.3861597  0.0421075  0.04847208 0.35100237]
[1 0 0] by nn
[0.19831753 0.42228583 0.0277397  0.04232116 0.30933583]
[1 0 0] by nn
[0.22081572 0.3920229  0.02550198 0.04463452 0.31702492]
[1 0 0] by nn
[0.1992819  0.4227523  0.02302377 0.03614099 0.31880108]
[1 0 0] 

[9.9992228e-01 3.3203345e-05 3.9365915e-09 4.4471424e-05 4.5573407e-19]
[-1  0  0] by nn
[9.9982929e-01 8.1876984e-05 1.5270629e-08 8.8779627e-05 9.6969176e-18]
[-1  0  0] by nn
[9.9972004e-01 1.3496612e-04 3.5006039e-08 1.4498764e-04 1.3495874e-16]
[-1  0  0] by nn
[9.9956697e-01 1.9565641e-04 1.5128580e-07 2.3718178e-04 3.0647628e-15]
[-1  0  0] by nn
[9.9905938e-01 4.0918731e-04 6.4287138e-07 5.3075631e-04 3.7358674e-13]
[-1  0  0] by nn
[9.9835807e-01 8.7895396e-04 3.0103956e-06 7.6001312e-04 1.4682183e-11]
[-1  0  0] by nn
[9.9192625e-01 5.5839075e-03 3.8856499e-05 2.4510941e-03 4.9268280e-08]
[-1  0  0] by nn
[9.72255528e-01 1.65792853e-02 4.17625793e-04 1.07107945e-02
 3.67642206e-05]
[-1  0  0] by nn
[0.9523933  0.02367373 0.00192888 0.02086383 0.00114032]
[-1  0  0] by nn
[0.90935296 0.03074048 0.00519016 0.02954216 0.02517432]
[-1  0  0] by nn
[0.8544022  0.0331151  0.00794244 0.04163674 0.06290364]
[-1  0  0] by nn
[0.82074416 0.04088973 0.0093321  0.04120739 0.08782655]
[-1

[0.40185615 0.1518965  0.07888681 0.1206717  0.24668886]
[0 1 0] by nn
[0.26524913 0.22941366 0.11856697 0.09955445 0.2872158 ]
[1 0 0] by nn
[0.18538347 0.29056528 0.13613069 0.0796245  0.3082961 ]
[1 0 0] by nn
[0.14540254 0.33262125 0.14072193 0.06936989 0.31188443]
[1 0 0] by nn
[0.12861958 0.40758523 0.13221246 0.06130582 0.2702769 ]
[1 0 0] by nn
[0.11826045 0.49979755 0.11422731 0.05175203 0.21596271]
[1 0 0] by nn
[0.1301557  0.48027995 0.09121052 0.05546784 0.242886  ]
[1 0 0] by nn
[0.11226062 0.41026396 0.11605865 0.06974053 0.29167622]
[1 0 0] by nn
[0.15042312 0.41603482 0.07203606 0.06220741 0.29929852]
[1 0 0] by nn
[0.17000178 0.3208321  0.07188278 0.06487307 0.3724103 ]
[1 0 0] by nn
[0.20868322 0.29646122 0.05743856 0.0508007  0.3866163 ]
[1 0 0] by nn
[0.24776284 0.27348387 0.05098107 0.05505538 0.37271687]
[1 0 0] by nn
[0.3010289  0.22202449 0.04963844 0.05855993 0.36874825]
[1 0 0] by nn
[0.2853202  0.20881782 0.04606842 0.05836784 0.40142572]
[1 0 0] by nn
[0.310

[0.8634848  0.02810501 0.00439794 0.02676073 0.07725154]
[-1  0  0] by nn
[0.8758736  0.0215579  0.00344483 0.02163416 0.0774895 ]
[-1  0  0] by nn
[0.86586356 0.02053342 0.00453994 0.02372638 0.08533666]
[-1  0  0] by nn
[0.8469757  0.02575681 0.00565862 0.02659018 0.09501882]
[-1  0  0] by nn
[0.81925625 0.03409119 0.00832    0.03470964 0.10362296]
[-1  0  0] by nn
[0.8374666  0.03180326 0.00708656 0.03192087 0.09172267]
[-1  0  0] by nn
[0.8072174  0.0364197  0.00862086 0.03888512 0.10885693]
[-1  0  0] by nn
[0.77683914 0.0397191  0.01064181 0.05026352 0.12253651]
[-1  0  0] by nn
[0.73838663 0.05813152 0.01982389 0.05503344 0.12862454]
[-1  0  0] by nn
[0.63690025 0.10073737 0.04825023 0.07452363 0.13958855]
[-1  0  0] by nn
[0.4741359  0.16082086 0.11821065 0.0960101  0.1508225 ]
[-1  0  0] by nn
[0.31526312 0.25333473 0.19735518 0.08959197 0.14445508]
[1 0 0] by nn
[0.19807632 0.3415633  0.2544482  0.06484712 0.141065  ]
[1 0 0] by nn
[0.14865035 0.45936337 0.19229425 0.05094671

[0.15000434 0.50863284 0.07541993 0.04047558 0.22546732]
[1 0 0] by nn
[0.14592776 0.5068531  0.05421673 0.04129731 0.25170517]
[1 0 0] by nn
[0.169561   0.4789631  0.03837585 0.04137199 0.2717281 ]
[1 0 0] by nn
[0.16664353 0.48020044 0.03335794 0.05013591 0.26966214]
[1 0 0] by nn
[0.15017012 0.4689615  0.03761251 0.0600156  0.28324023]
[1 0 0] by nn
[0.17054133 0.48965222 0.03039484 0.05429265 0.25511906]
[1 0 0] by nn
[0.1786356  0.444784   0.02934871 0.04862769 0.29860404]
[1 0 0] by nn
[0.17921811 0.43873903 0.03379542 0.04305034 0.30519718]
[1 0 0] by nn
[0.18350537 0.39107212 0.03748964 0.04111708 0.34681585]
[1 0 0] by nn
[0.2360247  0.3026085  0.05158411 0.04327249 0.3665102 ]
[1 0 0] by nn
[0.28364944 0.19880125 0.0751868  0.03821569 0.4041468 ]
[0 1 0] by nn
[0.40727466 0.12616214 0.05672017 0.03841096 0.37143204]
[0 1 0] by nn
[0.49685442 0.08848216 0.03453872 0.04211436 0.33801034]
[-1  0  0] by nn
[0.57060236 0.07601214 0.02472226 0.037501   0.29116222]
[-1  0  0] by nn


[1 0 0] by nn
[0.17228729 0.3850867  0.05369746 0.03886268 0.35006592]
[1 0 0] by nn
[0.20207398 0.28429902 0.07555391 0.04530582 0.39276725]
[1 0 0] by nn
[0.24781735 0.17998098 0.11187079 0.04958136 0.41074947]
[0 1 0] by nn
Track generation: 1275..1598 -> 323-tiles track
[4.7221249e-05 1.9628758e-04 1.5701357e-10 3.5686833e-03 9.9618787e-01]
[-1  0  0] by nn
[1.9008124e-21 8.8942360e-12 4.9568959e-24 4.4341553e-09 1.0000000e+00]
[-1  0  0] by nn
[2.0795159e-22 3.0247442e-14 9.8423471e-27 8.3120057e-07 9.9999917e-01]
[-1  0  0] by nn
[5.6401167e-10 1.4480586e-08 3.5417630e-13 6.2323324e-10 1.0000000e+00]
[-1  0  0] by nn
[6.8736094e-01 9.2946731e-02 1.2427786e-05 2.1815029e-01 1.5296647e-03]
[-1  0  0] by nn
[9.1125244e-01 2.5866481e-02 4.1235903e-06 6.2869728e-02 7.3123583e-06]
[-1  0  0] by nn
[9.9065876e-01 2.7577735e-03 2.0949582e-07 6.5832436e-03 9.3970929e-09]
[-1  0  0] by nn
[9.9422824e-01 1.0616027e-03 1.5499128e-07 4.7099763e-03 7.7635809e-09]
[-1  0  0] by nn
[9.9400324e-0

[0.6365461  0.181777   0.02424934 0.13742208 0.02000544]
[-1  0  0] by nn
[0.7212365  0.15003608 0.01399672 0.111696   0.00303471]
[-1  0  0] by nn
[0.74961406 0.15071683 0.01238923 0.08607744 0.0012024 ]
[-1  0  0] by nn
[7.6665145e-01 1.3348316e-01 1.4795198e-02 8.4433816e-02 6.3638750e-04]
[-1  0  0] by nn
[7.9677206e-01 1.2134712e-01 9.7648520e-03 7.1889378e-02 2.2664566e-04]
[-1  0  0] by nn
[8.3315462e-01 9.6665047e-02 8.0945790e-03 6.1792687e-02 2.9310319e-04]
[-1  0  0] by nn
[8.5000944e-01 9.2856392e-02 6.0077645e-03 5.0735161e-02 3.9125886e-04]
[-1  0  0] by nn
[0.8652224  0.0847162  0.00672139 0.04147384 0.00186616]
[-1  0  0] by nn
[0.8519196  0.09095517 0.01087592 0.03848224 0.00776701]
[-1  0  0] by nn
[0.8475313  0.05618387 0.01189059 0.03853557 0.04585867]
[-1  0  0] by nn
[0.8340536  0.04413591 0.0112635  0.03587242 0.07467461]
[-1  0  0] by nn
[0.8226805  0.03963494 0.01165478 0.03915704 0.08687273]
[-1  0  0] by nn
[0.8315251  0.03302791 0.01010572 0.03267837 0.09266

[0.16719222 0.63759464 0.00813951 0.02870219 0.15837146]
[1 0 0] by nn
[0.14701293 0.65104145 0.01075175 0.02923977 0.16195403]
[1 0 0] by nn
[0.1254049  0.66784483 0.01438934 0.03105002 0.16131085]
[1 0 0] by nn
[0.13091342 0.5913324  0.01911862 0.03997318 0.21866246]
[1 0 0] by nn
[0.15249245 0.50189626 0.03007497 0.04485088 0.27068543]
[1 0 0] by nn
[0.18311639 0.41634876 0.05375335 0.05188723 0.29489422]
[1 0 0] by nn
[0.21846074 0.29270148 0.0987631  0.06040193 0.32967275]
[1 0 0] by nn
[0.2604928  0.19979641 0.13634425 0.066331   0.33703557]
[0 1 0] by nn
[0.3423032  0.12867893 0.11945605 0.07089978 0.33866206]
[0 1 0] by nn
[0.51470745 0.08171023 0.06174164 0.06582683 0.2760139 ]
[-1  0  0] by nn
[0.6627882  0.0486394  0.02369581 0.03992051 0.22495608]
[-1  0  0] by nn
[0.7581059  0.03185179 0.00992124 0.02822587 0.17189531]
[-1  0  0] by nn
[0.81366974 0.02676502 0.00558408 0.02423345 0.12974767]
[-1  0  0] by nn
[0.832498   0.02690305 0.00454857 0.02155028 0.11450013]
[-1  0  

[8.5339504e-01 1.3584538e-01 1.6779170e-03 9.0350937e-03 4.6493602e-05]
[-1  0  0] by nn
[8.4534997e-01 1.4291218e-01 1.9323236e-03 9.7585162e-03 4.7106209e-05]
[-1  0  0] by nn
[8.4786874e-01 1.3975339e-01 1.8920861e-03 1.0449236e-02 3.6545996e-05]
[-1  0  0] by nn
[8.4066480e-01 1.4781745e-01 1.7234973e-03 9.7659631e-03 2.8375423e-05]
[-1  0  0] by nn
[8.5084039e-01 1.3832250e-01 1.5533784e-03 9.2652189e-03 1.8457584e-05]
[-1  0  0] by nn
[8.5815519e-01 1.3236576e-01 1.2978428e-03 8.1708226e-03 1.0309834e-05]
[-1  0  0] by nn
[8.5529894e-01 1.3678651e-01 1.2279354e-03 6.6791563e-03 7.4294303e-06]
[-1  0  0] by nn
[8.77507091e-01 1.14813015e-01 8.62011686e-04 6.81370450e-03
 4.13407997e-06]
[-1  0  0] by nn
[8.8938415e-01 1.0382851e-01 7.2211621e-04 6.0624820e-03 2.7296635e-06]
[-1  0  0] by nn
[8.9627451e-01 9.7712800e-02 5.7828770e-04 5.4319999e-03 2.3032362e-06]
[-1  0  0] by nn
[8.8941258e-01 1.0483629e-01 5.6373869e-04 5.1846476e-03 2.6886453e-06]
[-1  0  0] by nn
[9.0418947e-01 

[0.21954143 0.47071642 0.10695881 0.0434761  0.15930724]
[1 0 0] by nn
[0.15914376 0.5435032  0.07001091 0.03589857 0.19144358]
[1 0 0] by nn
[0.15291472 0.58483446 0.04374668 0.0346518  0.18385236]
[1 0 0] by nn
[0.17599088 0.56178695 0.03008204 0.03292521 0.19921483]
[1 0 0] by nn
[0.1761151  0.5650163  0.02585927 0.03699603 0.19601315]
[1 0 0] by nn
[0.16324319 0.5546958  0.02875094 0.04718184 0.20612824]
[1 0 0] by nn
[0.17930818 0.5718074  0.02147391 0.03908968 0.18832083]
[1 0 0] by nn
[0.17949618 0.53084165 0.02260043 0.04079716 0.22626452]
[1 0 0] by nn
[0.16586265 0.551728   0.01984648 0.0321424  0.23042046]
[1 0 0] by nn
[0.1438976  0.523576   0.02397937 0.03645366 0.2720934 ]
[1 0 0] by nn
[0.15882984 0.464521   0.03087801 0.03659705 0.30917412]
[1 0 0] by nn
[0.17066963 0.42227247 0.0453711  0.03555178 0.32613498]
[1 0 0] by nn
[0.22317526 0.35372314 0.06214838 0.04036843 0.3205848 ]
[1 0 0] by nn
[0.2724833  0.24992083 0.09373429 0.04978038 0.33408123]
[1 0 0] by nn
[0.341

[0.6732743  0.05882704 0.00887907 0.02754202 0.23147751]
[-1  0  0] by nn
[0.58271605 0.076303   0.01420861 0.05472092 0.27205145]
[-1  0  0] by nn
[0.65034866 0.06718452 0.0116241  0.04684163 0.22400114]
[-1  0  0] by nn
[0.6293948  0.07620066 0.01585977 0.0511666  0.2273782 ]
[-1  0  0] by nn
[0.56548464 0.11904699 0.02039684 0.07516354 0.21990797]
[-1  0  0] by nn
[0.5867405  0.13565686 0.02189198 0.08291101 0.17279966]
[-1  0  0] by nn
[0.5624722  0.18959512 0.02533302 0.0820599  0.14053974]
[-1  0  0] by nn
[0.46946147 0.27511173 0.03353727 0.08332491 0.13856456]
[-1  0  0] by nn
[0.41274375 0.35396606 0.03195718 0.07794076 0.12339228]
[1 0 0] by nn
[0.3078494  0.41136813 0.03105861 0.07867432 0.17104952]
[1 0 0] by nn
[0.2292133  0.45699438 0.02880956 0.08286784 0.20211488]
[1 0 0] by nn
[0.23117626 0.4538316  0.02714034 0.06841209 0.21943967]
[1 0 0] by nn
[0.26872033 0.40278584 0.02275292 0.07989129 0.22584958]
[1 0 0] by nn
[0.32137513 0.35353178 0.01616501 0.06886514 0.240062

[0.54775506 0.104424   0.03662496 0.05252833 0.25866768]
[-1  0  0] by nn
[0.45729047 0.14068036 0.05878307 0.07649466 0.26675144]
[-1  0  0] by nn
[0.45638534 0.17541172 0.06941333 0.07990715 0.21888246]
[-1  0  0] by nn
[0.45658365 0.19912311 0.09114593 0.0760214  0.17712586]
[-1  0  0] by nn
[0.34466773 0.27350974 0.1418754  0.08247677 0.15747043]
[1 0 0] by nn
[0.16741292 0.37555143 0.23940617 0.06908488 0.1485446 ]
[1 0 0] by nn
[0.1405305  0.4242633  0.22740106 0.05559726 0.15220787]
[1 0 0] by nn
[0.11521574 0.54997647 0.15445204 0.04533346 0.13502228]
[1 0 0] by nn
[0.13501549 0.61689955 0.06363741 0.04264926 0.14179827]
[1 0 0] by nn
[0.15259477 0.6267858  0.03879062 0.0373189  0.14450994]
[1 0 0] by nn
[0.1934309  0.59709936 0.02271662 0.043436   0.14331712]
[1 0 0] by nn
[0.17856455 0.5684941  0.02914011 0.05675248 0.16704875]
[1 0 0] by nn
[0.19623382 0.5836409  0.02081912 0.0504787  0.14882745]
[1 0 0] by nn
[0.20625988 0.5262683  0.02173199 0.05388242 0.19185747]
[1 0 0] 

[0.16373384 0.36491746 0.16102631 0.05349202 0.25683036]
[1 0 0] by nn
[0.16975686 0.40195504 0.11385746 0.04787751 0.2665531 ]
[1 0 0] by nn
[0.16660488 0.43295947 0.08584978 0.04798461 0.2666013 ]
[1 0 0] by nn
[0.14195542 0.4244921  0.09567859 0.05623261 0.2816413 ]
[1 0 0] by nn
[0.15861705 0.46247387 0.06959515 0.04916191 0.26015204]
[1 0 0] by nn
[0.1589784  0.4350554  0.07971119 0.05103657 0.27521843]
[1 0 0] by nn
[0.18433665 0.410746   0.07711568 0.0476654  0.2801363 ]
[1 0 0] by nn
[0.17871748 0.36326152 0.09484427 0.05834944 0.30482727]
[1 0 0] by nn
[0.22565629 0.27317965 0.1202131  0.06854346 0.3124075 ]
[1 0 0] by nn
[0.26104578 0.20706238 0.14258151 0.07829016 0.31102014]
[1 0 0] by nn
[0.3832208  0.15584825 0.1288798  0.08038761 0.25166357]
[0 1 0] by nn
[0.5130563  0.11759696 0.07148597 0.06750271 0.23035811]
[-1  0  0] by nn
[0.6971116  0.06361707 0.0270403  0.04165828 0.17057276]
[-1  0  0] by nn
[0.7570564  0.05434395 0.01252827 0.0339879  0.14208353]
[-1  0  0] by 

[0.73994595 0.06336509 0.02381122 0.05017029 0.12270755]
[-1  0  0] by nn
[0.65728277 0.08865806 0.04585247 0.07250819 0.13569851]
[-1  0  0] by nn
[0.60389996 0.13481899 0.05770088 0.07863431 0.12494583]
[-1  0  0] by nn
[0.4524699  0.23505393 0.0818356  0.08738319 0.14325736]
[-1  0  0] by nn
[0.29823348 0.4394671  0.07783614 0.0620984  0.12236491]
[1 0 0] by nn
[0.21485549 0.5647192  0.04133603 0.04147959 0.13760965]
[1 0 0] by nn
[0.1217315  0.6312257  0.02251742 0.02825067 0.1962748 ]
[1 0 0] by nn
[0.11958591 0.6430024  0.01184485 0.02253333 0.20303348]
[1 0 0] by nn
[0.15843292 0.58277154 0.00854286 0.02659341 0.22365929]
[1 0 0] by nn
[0.20647526 0.5272434  0.00583043 0.03022262 0.23022829]
[1 0 0] by nn
[0.2583493  0.45453796 0.00608425 0.03461908 0.2464094 ]
[1 0 0] by nn
[0.23042753 0.43201873 0.00768431 0.04622915 0.28364027]
[1 0 0] by nn
[0.24942379 0.4427168  0.00513553 0.03397977 0.26874405]
[1 0 0] by nn
[0.23784721 0.39999938 0.00581382 0.03892311 0.31741646]
[1 0 0] 

[1 0 0] by nn
[0.22349377 0.1738451  0.14707004 0.05244024 0.40315086]
[0 1 0] by nn
[0.32402    0.10610888 0.12785558 0.06162359 0.380392  ]
[0 1 0] by nn
[0.3947778  0.09440437 0.09184981 0.06796355 0.35100448]
[0 1 0] by nn
[0.47959074 0.08653644 0.06683381 0.06134803 0.305691  ]
[-1  0  0] by nn
[0.5145914  0.08641538 0.05762256 0.06603512 0.27533543]
[-1  0  0] by nn
[0.5196399  0.08326475 0.05647552 0.06501434 0.2756055 ]
[-1  0  0] by nn
[0.46368217 0.08550558 0.07233765 0.07650524 0.30196932]
[-1  0  0] by nn
[0.5096992  0.09348267 0.05676053 0.06283686 0.27722076]
[-1  0  0] by nn
[0.43700045 0.1031996  0.07343985 0.07326815 0.313092  ]
[0 1 0] by nn
[0.40926552 0.11782498 0.08045142 0.06802426 0.3244338 ]
[0 1 0] by nn
[0.34731093 0.09960961 0.10048928 0.07908475 0.37350544]
[0 1 0] by nn
[0.41051966 0.09114312 0.081015   0.07554669 0.3417755 ]
[0 1 0] by nn
[0.4277773  0.09042414 0.07503003 0.07141344 0.33535513]
[0 1 0] by nn
[0.4437442  0.08701027 0.07066192 0.06881553 0.3

[0.42766047 0.11553211 0.05157894 0.0737491  0.33147943]
[0 1 0] by nn
[0.42618877 0.11884125 0.05231617 0.07854676 0.32410702]
[0 1 0] by nn
[0.44092664 0.11113447 0.05302523 0.08713259 0.30778107]
[0 1 0] by nn
[0.44145787 0.10738935 0.05155256 0.09276493 0.30683532]
[0 1 0] by nn
[0.4649289  0.10238742 0.04911363 0.0928091  0.29076102]
[-1  0  0] by nn
[0.52814484 0.08846388 0.03437487 0.07896996 0.27004644]
[-1  0  0] by nn
[0.59487104 0.08592422 0.02600147 0.06388482 0.22931845]
[-1  0  0] by nn
[0.60327435 0.09099912 0.02726834 0.05880254 0.2196556 ]
[-1  0  0] by nn
[0.557698   0.10311185 0.03897232 0.07262053 0.22759727]
[-1  0  0] by nn
[0.5383708  0.11129145 0.04564032 0.07775522 0.22694229]
[-1  0  0] by nn
[0.5561943  0.11648621 0.04345626 0.09007628 0.19378696]
[-1  0  0] by nn
[0.618404   0.1070612  0.03953073 0.08514531 0.14985874]
[-1  0  0] by nn
[0.5839913  0.12334134 0.03901915 0.07511997 0.17852825]
[-1  0  0] by nn
[0.56377107 0.1323596  0.04271242 0.08034626 0.180

[0.16356039 0.6166886  0.00852144 0.04031983 0.17090973]
[1 0 0] by nn
[0.13950464 0.64492226 0.01015425 0.03607636 0.16934249]
[1 0 0] by nn
[0.11426548 0.63700783 0.01942645 0.03905844 0.19024172]
[1 0 0] by nn
[0.11114453 0.62858003 0.01731712 0.04683256 0.19612575]
[1 0 0] by nn
[0.12570514 0.5792648  0.02592206 0.05232912 0.21677886]
[1 0 0] by nn
[0.15225388 0.50771254 0.04871782 0.05464499 0.2366708 ]
[1 0 0] by nn
[0.182233   0.39224392 0.0888783  0.06110103 0.27554375]
[1 0 0] by nn
[0.20921913 0.27903566 0.11384399 0.05676048 0.34114078]
[1 0 0] by nn
[0.25893992 0.20189433 0.12022188 0.05424844 0.36469537]
[1 0 0] by nn
[0.3847227  0.14660293 0.08630206 0.05123923 0.33113304]
[0 1 0] by nn
[0.538113   0.09398001 0.04151259 0.04389109 0.28250334]
[-1  0  0] by nn
[0.6035724  0.05938629 0.02728232 0.04013622 0.26962274]
[-1  0  0] by nn
[0.68230486 0.04576454 0.02164153 0.04046155 0.20982756]
[-1  0  0] by nn
[0.80437887 0.03316967 0.01063624 0.03096468 0.12085047]
[-1  0  0] 

[9.5331419e-01 3.8214084e-02 5.1549752e-04 7.9548452e-03 1.3094349e-06]
[-1  0  0] by nn
[9.4772291e-01 4.3560661e-02 5.1643356e-04 8.1980675e-03 1.9207232e-06]
[-1  0  0] by nn
[9.4207776e-01 5.0343126e-02 5.0718780e-04 7.0701530e-03 1.7526744e-06]
[-1  0  0] by nn
[9.4053859e-01 5.2239202e-02 4.5127163e-04 6.7698783e-03 1.1694990e-06]
[-1  0  0] by nn
[9.3508726e-01 5.7621248e-02 3.6629962e-04 6.9242073e-03 9.3385717e-07]
[-1  0  0] by nn
[9.2459631e-01 6.7287594e-02 4.1327023e-04 7.7012288e-03 1.4934119e-06]
[-1  0  0] by nn
[9.3846297e-01 5.5599224e-02 2.6092315e-04 5.6763203e-03 5.4320532e-07]
[-1  0  0] by nn
[9.3367130e-01 6.1190791e-02 2.4748873e-04 4.8899343e-03 5.5196818e-07]
[-1  0  0] by nn
[9.4028258e-01 5.4092471e-02 1.9829991e-04 5.4261424e-03 4.8606881e-07]
[-1  0  0] by nn
[9.4605690e-01 4.9111802e-02 1.7093732e-04 4.6597221e-03 6.3535174e-07]
[-1  0  0] by nn
[9.4020164e-01 5.4783531e-02 2.2610622e-04 4.7873082e-03 1.4717390e-06]
[-1  0  0] by nn
[9.3316048e-01 6.1578

[8.46572220e-01 1.39949098e-01 4.65021376e-03 8.81325640e-03
 1.52302855e-05]
[-1  0  0] by nn
[8.6698472e-01 1.2232349e-01 3.3970263e-03 7.2825132e-03 1.2163727e-05]
[-1  0  0] by nn
[8.69984329e-01 1.19584575e-01 2.83835293e-03 7.58460676e-03
 8.04929641e-06]
[-1  0  0] by nn
[8.9668858e-01 9.3671046e-02 1.9562282e-03 7.6818769e-03 2.2069887e-06]
[-1  0  0] by nn
[9.1179472e-01 8.0473617e-02 1.3656945e-03 6.3651740e-03 7.9673197e-07]
[-1  0  0] by nn
[9.1549885e-01 7.7038974e-02 1.1178876e-03 6.3434192e-03 8.8919444e-07]
[-1  0  0] by nn
[8.9701098e-01 9.4062477e-02 1.3663839e-03 7.5579342e-03 2.2759145e-06]
[-1  0  0] by nn
[8.7618476e-01 1.1332923e-01 2.0827265e-03 8.3928946e-03 1.0329882e-05]
[-1  0  0] by nn
[8.63153219e-01 1.24610536e-01 3.43975378e-03 8.76974501e-03
 2.67208816e-05]
[-1  0  0] by nn
[8.4584641e-01 1.4142132e-01 3.5557724e-03 9.1496138e-03 2.6811544e-05]
[-1  0  0] by nn
[8.1499648e-01 1.7142087e-01 4.4121570e-03 9.1348030e-03 3.5718585e-05]
[-1  0  0] by nn
[7.

[8.4652960e-01 1.4343835e-01 2.5759407e-03 6.8829195e-03 5.7323615e-04]
[-1  0  0] by nn
[8.3488333e-01 1.5486726e-01 2.7466097e-03 6.8847472e-03 6.1805348e-04]
[-1  0  0] by nn
[8.1365025e-01 1.7555313e-01 3.0864216e-03 6.8977643e-03 8.1238517e-04]
[-1  0  0] by nn
[0.79346716 0.1951246  0.00374209 0.00651774 0.00114841]
[-1  0  0] by nn
[0.78880525 0.19973788 0.00374556 0.00651365 0.00119768]
[-1  0  0] by nn
[0.78961927 0.19902581 0.00363195 0.00657758 0.0011454 ]
[-1  0  0] by nn
[0.8025857  0.18649934 0.00346241 0.00650534 0.00094721]
[-1  0  0] by nn
[8.1367821e-01 1.7609084e-01 2.9574458e-03 6.5504764e-03 7.2302145e-04]
[-1  0  0] by nn
[8.2372743e-01 1.6631052e-01 2.6166958e-03 6.7903320e-03 5.5492023e-04]
[-1  0  0] by nn
[8.1769454e-01 1.7257495e-01 2.7932618e-03 6.4239255e-03 5.1329372e-04]
[-1  0  0] by nn
[8.2012880e-01 1.6960803e-01 2.8032276e-03 7.0377397e-03 4.2230080e-04]
[-1  0  0] by nn
[8.2669741e-01 1.6298322e-01 2.6408173e-03 7.3404117e-03 3.3812487e-04]
[-1  0  0

[0.6468962  0.21038488 0.00447356 0.01785194 0.12039343]
[-1  0  0] by nn
[0.64596224 0.21996978 0.00485199 0.01982013 0.10939578]
[-1  0  0] by nn
[0.64336    0.24465646 0.00631816 0.02378868 0.08187664]
[-1  0  0] by nn
[0.6571996  0.25125974 0.00715617 0.02644828 0.05793612]
[-1  0  0] by nn
[0.6187475  0.30667815 0.00720484 0.02621497 0.0411546 ]
[-1  0  0] by nn
[0.5990729  0.34768027 0.00657712 0.02548436 0.02118532]
[-1  0  0] by nn
[0.58942986 0.36360395 0.0062862  0.02560091 0.01507912]
[-1  0  0] by nn
[0.60103226 0.35958394 0.00498067 0.02363655 0.01076648]
[-1  0  0] by nn
[0.6106374  0.35832432 0.00320184 0.02030651 0.00752991]
[-1  0  0] by nn
[0.6107023  0.35393804 0.00306882 0.02632548 0.00596541]
[-1  0  0] by nn
[0.63491726 0.34250173 0.00124854 0.01853269 0.00279983]
[-1  0  0] by nn
[6.8826222e-01 2.9611707e-01 5.5341003e-04 1.3944475e-02 1.1227762e-03]
[-1  0  0] by nn
[7.1346056e-01 2.7631465e-01 2.3445686e-04 9.6225673e-03 3.6788249e-04]
[-1  0  0] by nn
[7.72376

[-1  0  0] by nn
[8.7193859e-01 1.1765991e-01 1.7710703e-03 7.9926485e-03 6.3784013e-04]
[-1  0  0] by nn
[8.6142355e-01 1.2815528e-01 1.9889430e-03 7.6495982e-03 7.8263099e-04]
[-1  0  0] by nn
[8.5657579e-01 1.3230886e-01 2.1773921e-03 8.0841128e-03 8.5375813e-04]
[-1  0  0] by nn
[0.8479096  0.1406387  0.00259434 0.00777646 0.00108096]
[-1  0  0] by nn
[0.8433307  0.1448947  0.00287792 0.00769102 0.0012057 ]
[-1  0  0] by nn
[0.83797306 0.14974843 0.00329895 0.00762682 0.00135273]
[-1  0  0] by nn
[0.83202785 0.15536004 0.00360603 0.00742987 0.00157627]
[-1  0  0] by nn
[0.8244009  0.16232158 0.00392111 0.00756764 0.0017887 ]
[-1  0  0] by nn
[0.8175094  0.16983877 0.00416795 0.00681426 0.00166963]
[-1  0  0] by nn
[0.8080578  0.17911592 0.00409247 0.0071127  0.00162114]
[-1  0  0] by nn
[0.80016965 0.18701223 0.004059   0.00720751 0.00155162]
[-1  0  0] by nn
[0.7951748  0.19270492 0.00379442 0.00701475 0.00131118]
[-1  0  0] by nn
[0.7925284  0.19592167 0.00363968 0.00678102 0.001

[9.8995399e-01 8.0049159e-03 1.1474990e-05 2.0294443e-03 5.9984579e-08]
[-1  0  0] by nn
[9.8954272e-01 8.1827072e-03 1.7719978e-05 2.2567122e-03 9.3121159e-08]
[-1  0  0] by nn
[9.8909724e-01 8.8737728e-03 2.2075592e-05 2.0068348e-03 8.6619835e-08]
[-1  0  0] by nn
[9.87367809e-01 1.07987663e-02 3.11184267e-05 1.80212338e-03
 1.11315664e-07]
[-1  0  0] by nn
[9.8701930e-01 1.1137985e-02 3.3638564e-05 1.8088883e-03 1.3449348e-07]
[-1  0  0] by nn
[9.8545724e-01 1.2415266e-02 4.7386391e-05 2.0799155e-03 2.8857065e-07]
[-1  0  0] by nn
[9.85670507e-01 1.16888955e-02 5.32817612e-05 2.58694403e-03
 3.40734715e-07]
[-1  0  0] by nn
[9.8423529e-01 1.2980759e-02 5.3442120e-05 2.7299246e-03 4.2473809e-07]
[-1  0  0] by nn
[9.8397022e-01 1.3445277e-02 6.2194835e-05 2.5215447e-03 6.5187527e-07]
[-1  0  0] by nn
[9.84649122e-01 1.34626785e-02 6.55927652e-05 1.82163203e-03
 9.78412913e-07]
[-1  0  0] by nn
[9.8294121e-01 1.5160406e-02 8.0312275e-05 1.8163397e-03 1.7107975e-06]
[-1  0  0] by nn
[9.

[-1  0  0] by nn
[8.85687888e-01 1.08729206e-01 5.28030505e-04 5.03367092e-03
 2.12212217e-05]
[-1  0  0] by nn
[9.3374497e-01 6.2286630e-02 1.3574473e-04 3.8294562e-03 3.1030875e-06]
[-1  0  0] by nn
[9.4888359e-01 4.7903232e-02 5.6193214e-05 3.1563442e-03 6.5882801e-07]
[-1  0  0] by nn
[9.6267724e-01 3.4956601e-02 2.3830522e-05 2.3421564e-03 1.3474725e-07]
[-1  0  0] by nn
[9.7352725e-01 2.4623379e-02 1.2032460e-05 1.8373367e-03 3.0343749e-08]
[-1  0  0] by nn
[9.7973633e-01 1.8609777e-02 6.6617922e-06 1.6472944e-03 9.3980503e-09]
[-1  0  0] by nn
[9.8490369e-01 1.3659220e-02 3.4027278e-06 1.4337186e-03 3.0329046e-09]
[-1  0  0] by nn
[9.8775464e-01 1.1109421e-02 2.0937759e-06 1.1338034e-03 1.2132998e-09]
[-1  0  0] by nn
[9.9047989e-01 8.5481117e-03 1.4051092e-06 9.7056525e-04 6.4848399e-10]
[-1  0  0] by nn
[9.9186397e-01 7.2418088e-03 9.7970053e-07 8.9322124e-04 3.3960693e-10]
[-1  0  0] by nn
[9.9297148e-01 6.0855155e-03 7.5026423e-07 9.4226404e-04 2.7250632e-10]
[-1  0  0] by n

[9.7098190e-01 2.5918802e-02 1.5607962e-04 2.9368056e-03 6.4308751e-06]
[-1  0  0] by nn
[9.6374255e-01 3.2502070e-02 2.2610452e-04 3.5195465e-03 9.5936593e-06]
[-1  0  0] by nn
[9.5989895e-01 3.5986591e-02 2.9924535e-04 3.8000559e-03 1.5130007e-05]
[-1  0  0] by nn
[9.5576119e-01 3.9255682e-02 3.8600148e-04 4.5688353e-03 2.8294036e-05]
[-1  0  0] by nn
[9.5979410e-01 3.5588037e-02 3.8637593e-04 4.2041130e-03 2.7366075e-05]
[-1  0  0] by nn
[9.5387644e-01 4.0580291e-02 4.5923900e-04 5.0345780e-03 4.9448667e-05]
[-1  0  0] by nn
[9.4271892e-01 5.0379843e-02 5.8315322e-04 6.2236264e-03 9.4366413e-05]
[-1  0  0] by nn
[9.2979914e-01 6.1852843e-02 8.0394611e-04 7.3877983e-03 1.5615385e-04]
[-1  0  0] by nn
[9.1045684e-01 8.0404200e-02 1.2053398e-03 7.6701897e-03 2.6345818e-04]
[-1  0  0] by nn
[8.87370408e-01 1.02689214e-01 1.59341283e-03 7.92256650e-03
 4.24413505e-04]
[-1  0  0] by nn
[8.87224913e-01 1.02698766e-01 1.53038907e-03 8.15106835e-03
 3.94866278e-04]
[-1  0  0] by nn
