In [40]:
# Importing Dependencies
import numpy as np
import gym
from gym.envs.box2d.car_racing import *
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPool2D, BatchNormalization
from keras.optimizers import Adam
from statistics import mean
from pyglet.window import key
import time
from tqdm import tqdm 
import os
from keras.utils import normalize

In [2]:
# Function for generating data by playing
def start_playing(n_episodes):
    a = np.array( [0.0, 0.0, 0.0] )
    def key_press(k, mod):
        global restart
        if k==0xff0d: restart = True
        if k==key.LEFT:  a[0] = -1.0
        if k==key.RIGHT: a[0] = +1.0
        if k==key.UP:    a[1] = +1.0
        if k==key.DOWN:  a[2] = +0.8   
    def key_release(k, mod):
        if k==key.LEFT  and a[0]==-1.0: a[0] = 0
        if k==key.RIGHT and a[0]==+1.0: a[0] = 0
        if k==key.UP:    a[1] = 0
        if k==key.DOWN:  a[2] = 0
    
    env = CarRacing()
    env.render()
    env.viewer.window.on_key_press = key_press
    env.viewer.window.on_key_release = key_release
    
    for episode in range(n_episodes):
        prev_observation = env.reset()
        if episode==0:
            X = np.array(prev_observation.tolist())
            y = np.array([0.,0.,0.])
        restart = False
        while True:
            action = a
            observation, reward, done, info = env.step(action)
            X = np.vstack((X, prev_observation))
            y = np.vstack((y, action))
            prev_observation=observation
            env.render()
            if done or restart: break
        time.sleep(2)    
    np.save('train_X.npy', X)
    np.save('train_y.npy', y)    
    env.close()
    return X, y

In [3]:
# Playing the to create data
X, y=start_playing(20)

Track generation: 1121..1405 -> 284-tiles track
Track generation: 925..1162 -> 237-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1228..1538 -> 310-tiles track
Track generation: 1132..1419 -> 287-tiles track
Track generation: 1282..1607 -> 325-tiles track
Track generation: 1171..1472 -> 301-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1120..1404 -> 284-tiles track
Track generation: 1030..1291 -> 261-tiles track
Track generation: 1119..1403 -> 284-tiles track
Track generation: 1126..1412 -> 286-tiles track
Track generation: 1413..1770 -> 357-tiles track
Track generation: 1230..1541 -> 311-tiles track
Track generation: 1246..1562 -> 316-tiles track
Track generation: 1128..1414 -> 286-tiles track
Track generation: 1085..1365 -> 280-tiles track
Track generation: 1387..1738 -> 351-tiles track
Track generation: 992..1251 -> 259-tiles track
Track generation: 1029..1296 -> 267-tiles 

In [8]:
# Combining gameplay files
temp = np.load('train_data-549.4999999999591.npy')
tempX = [i[0] for i in temp]
tempy = [i[1] for i in temp]
X = np.array(tempX)
y = np.array(tempy)
for file in tqdm(os.listdir('Data/')):
    temp = np.load('Data/' + file)
    tempX = [i[0] for i in temp]
    tempy = [i[1] for i in temp]
    tempX = np.array(tempX)
    tempy = np.array(tempy)
    X  = np.concatenate([X, tempX], axis=0)
    y  = np.concatenate([y, tempy], axis=0)

np.save('X.npy', X)    

100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:05<00:00,  1.60it/s]


In [5]:
# Converting output to proper OneHot array
Y=[]
for i in range(len(y)):  
    if np.array_equal(y[i], np.array([0,1,0])):
        Y.append(np.array([0,0,1,0,0]))
    elif np.array_equal(y[i], np.array([0,0,0.8])):
        Y.append(np.array([0,0,0,1,0]))
    elif np.array_equal(y[i], np.array([1,0,0])):
        Y.append(np.array([0,1,0,0,0]))
    elif np.array_equal(y[i], np.array([-1,0,0])):
        Y.append(np.array([1,0,0,0,0]))
    else:
        Y.append(np.array([0,0,0,0,1]))      
      
np.save('y_modified.npy', Y)    

In [41]:
# Loading the data
X = np.load('train_X.npy')
y = np.load('y_modified.npy')
X = X.reshape(-1,96,96,3)
print(X.shape)
print(y.shape)

(20450, 96, 96, 3)
(20450, 5)


In [23]:
# Variation in generated data
left=np.array([1,0,0,0,0])
right=np.array([0,1,0,0,0])
straight=np.array([0,0,1,0,0])
stop=np.array([0,0,0,1,0])
no_key=np.array([0,0,0,0,1])
l=0
r=0
s=0
b=0
nk=0

for key in y:
    if np.array_equal(key, left):
        l+=1
    elif np.array_equal(key, right):
        r+=1
    elif np.array_equal(key, straight):
        s+=1
    elif np.array_equal(key, stop):
        b+=1
    elif np.array_equal(key, no_key):
        nk+=1    
      
print(l,r,s,b,nk)    

2694 1318 4443 179 11816


In [56]:
model = Sequential()

model.add(Conv2D(filters = 16, kernel_size = (5,5),padding = 'Same', 
                 activation ='relu', input_shape = (96,96,3)))
model.add(Conv2D(filters = 16, kernel_size = (5,5),padding = 'Same', 
                 activation ='relu'))
model.add(BatchNormalization())
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Dropout(0.5))

model.add(Conv2D(filters = 32, kernel_size = (3,3),padding = 'Same', 
                 activation ='relu'))
model.add(Conv2D(filters = 32, kernel_size = (3,3),padding = 'Same', 
                 activation ='relu'))
model.add(BatchNormalization())
model.add(MaxPool2D(pool_size=(2,2), strides=(2,2)))
model.add(Dropout(0.5))


model.add(Flatten())
model.add(Dense(256, activation = "relu"))
model.add(BatchNormalization())
model.add(Dropout(0.5))

model.add(Dense(5, activation = "softmax"))

In [57]:
optimizer = Adam(lr=0.0001)
model.compile(optimizer = optimizer, loss = "categorical_crossentropy")

In [58]:
model.fit(X, y, epochs=10, validation_split=0.2, batch_size=600, verbose=1, shuffle=True)

Train on 16360 samples, validate on 4090 samples
Epoch 1/10
16360/16360 [==============================] - ETA: 53s - loss: 2.71 - ETA: 29s - loss: 2.62 - ETA: 21s - loss: 2.62 - ETA: 17s - loss: 2.57 - ETA: 14s - loss: 2.52 - ETA: 13s - loss: 2.52 - ETA: 11s - loss: 2.51 - ETA: 10s - loss: 2.49 - ETA: 9s - loss: 2.4639 - ETA: 8s - loss: 2.445 - ETA: 7s - loss: 2.415 - ETA: 7s - loss: 2.397 - ETA: 6s - loss: 2.383 - ETA: 6s - loss: 2.367 - ETA: 5s - loss: 2.350 - ETA: 4s - loss: 2.344 - ETA: 4s - loss: 2.343 - ETA: 3s - loss: 2.335 - ETA: 3s - loss: 2.331 - ETA: 3s - loss: 2.322 - ETA: 2s - loss: 2.312 - ETA: 2s - loss: 2.301 - ETA: 1s - loss: 2.286 - ETA: 1s - loss: 2.279 - ETA: 0s - loss: 2.267 - ETA: 0s - loss: 2.254 - ETA: 0s - loss: 2.248 - 12s 736us/step - loss: 2.2458 - val_loss: 1.8947
Epoch 2/10
16360/16360 [==============================] - ETA: 8s - loss: 1.943 - ETA: 8s - loss: 1.937 - ETA: 7s - loss: 1.924 - ETA: 7s - loss: 1.913 - ETA: 7s - loss: 1.931 - ETA: 7s - loss: 1

In [ ]:
# Saving the Model
model.save('Models/first_model')

In [ ]:
# Loading the Model
model.load('Models/first-model')

In [73]:
#scores = []
#choices = []
env = CarRacing()
for each_game in range(3):
    #score = 0
    #game_memory = []
    prev_obs = env.reset()
    for i in range(1000):
        env.render()
        out = model.predict(prev_obs.reshape(-1,96,96,3))[0]
        print(out)
        
        if out[0]<=0.35:
            out[0]=0  
        if out[1]<=0.2:
            out[1]=0
        if out[2]<=0.01 :
            out[2]=0   
        if out[3]<=0.47:
            out[3]=0
        if out[4]<=9:
            out[4]=0    
        
        output = np.argmax(out)
        action = np.zeros(5)
        np.put(action, output, 1)
        #choices.append(action)
        if np.array_equal(action, np.array([0,0,1,0,0])):
            action=np.array([0,1,0])
        elif np.array_equal(action, np.array([0,0,0,1,0])):
            action=np.array([0,0,0.8])
        elif np.array_equal(action, np.array([0,1,0,0,0])):
            action=np.array([1,0,0])
        elif np.array_equal(action, np.array([1,0,0,0,0])):
            action=np.array([-1,0,0])
        else:
            action=np.array([0,0,0,0,0])
        
        new_observation, reward, done, info = env.step(action)
        print(action,"by nn")
        prev_obs = new_observation
        #game_memory.append([new_observation, action])
        #score+=reward
        if done: 
            break
    #scores.append(score)
    #print('Episode {} Score: {}'.format(each_game+1,score))
    env.close()
#print('Average Score:',sum(scores)/len(scores))

Track generation: 1380..1729 -> 349-tiles track
[1.6442436e-04 2.2818191e-05 2.5397397e-03 1.0105422e-06 9.9727196e-01]
[-1  0  0] by nn
[3.52858931e-01 1.72678918e-01 3.48536996e-05 1.06162526e-01
 3.68264735e-01]
[-1  0  0] by nn
[8.3430775e-02 6.4376348e-01 3.6909637e-07 1.4804999e-02 2.5800034e-01]
[1 0 0] by nn
[2.7686701e-04 2.5917229e-01 2.8544762e-09 2.9073379e-03 7.3764348e-01]
[1 0 0] by nn
[6.1393544e-06 7.4700988e-03 6.8491657e-10 5.9846789e-04 9.9192530e-01]
[-1  0  0] by nn
[4.2761651e-05 1.8267358e-02 3.2690500e-10 3.4909819e-03 9.7819889e-01]
[-1  0  0] by nn
[3.8040183e-05 1.6056962e-02 4.3465129e-09 1.1993162e-03 9.8270571e-01]
[-1  0  0] by nn
[1.71740372e-02 1.10818565e-01 1.59154888e-06 3.72896120e-02
 8.34716201e-01]
[-1  0  0] by nn
[4.31500934e-03 1.04166046e-01 7.73821739e-06 3.16188261e-02
 8.59892368e-01]
[-1  0  0] by nn
[1.5594886e-02 2.2372605e-01 1.9868572e-05 1.6669667e-01 5.9396255e-01]
[1 0 0] by nn
[2.8853422e-02 6.7119919e-02 1.2578010e-05 9.6369669e

[0.86147386 0.01728413 0.00438677 0.09169513 0.02516014]
[-1  0  0] by nn
[0.902813   0.01143992 0.00405471 0.06596035 0.01573203]
[-1  0  0] by nn
[0.92813116 0.00824606 0.00340045 0.05010948 0.01011284]
[-1  0  0] by nn
[0.9422257  0.00767106 0.00283498 0.03997673 0.00729163]
[-1  0  0] by nn
[0.9498184  0.00583527 0.00256536 0.03526185 0.00651911]
[-1  0  0] by nn
[0.95736915 0.00372999 0.00210983 0.02935561 0.00743539]
[-1  0  0] by nn
[0.96268547 0.00274461 0.00207728 0.02263113 0.00986157]
[-1  0  0] by nn
[0.9584194  0.00259058 0.00252692 0.02393763 0.01252548]
[-1  0  0] by nn
[0.9579347  0.00222674 0.00260307 0.02122363 0.01601186]
[-1  0  0] by nn
[0.9480753  0.00248649 0.00314093 0.02110278 0.02519447]
[-1  0  0] by nn
[0.9394969  0.00268584 0.00316858 0.02203158 0.03261719]
[-1  0  0] by nn
[0.9251144  0.00279104 0.0033751  0.0255555  0.04316406]
[-1  0  0] by nn
[0.91627455 0.00366425 0.00415148 0.02855566 0.04735403]
[-1  0  0] by nn
[0.8902862  0.00670633 0.00730935 0.03

[0.83124197 0.00730321 0.00857822 0.03821076 0.11466583]
[-1  0  0] by nn
[0.83124524 0.00566796 0.00837427 0.04913115 0.10558127]
[-1  0  0] by nn
[0.89404225 0.00325165 0.00258542 0.03387998 0.06624063]
[-1  0  0] by nn
[0.89009273 0.00303483 0.00295934 0.03432702 0.06958614]
[-1  0  0] by nn
[0.91326356 0.0038512  0.00193643 0.02351263 0.05743631]
[-1  0  0] by nn
[0.9121719  0.00410465 0.00229975 0.02316679 0.05825686]
[-1  0  0] by nn
[0.8942213  0.00515931 0.00443735 0.02866296 0.06751908]
[-1  0  0] by nn
[0.8910106  0.00793569 0.00679902 0.03267138 0.06158344]
[-1  0  0] by nn
[0.87923527 0.01085331 0.01192016 0.03285691 0.06513433]
[-1  0  0] by nn
[0.7563993  0.0240909  0.04033165 0.05329049 0.12588769]
[-1  0  0] by nn
[0.5720524  0.05630963 0.08800645 0.08905669 0.19457485]
[-1  0  0] by nn
[0.3022453  0.11449333 0.1263833  0.14959028 0.3072878 ]
[0 1 0] by nn
[0.10534015 0.21078189 0.11400131 0.1389725  0.4309041 ]
[1 0 0] by nn
[0.03587022 0.38884246 0.0816846  0.08238476

 3.92711739e-31]
[-1  0  0] by nn
[9.9999845e-01 2.9749654e-09 3.2524232e-14 1.5309365e-06 1.6279681e-32]
[-1  0  0] by nn
[9.9999845e-01 2.4792843e-09 1.2707287e-14 1.4927308e-06 1.0115612e-32]
[-1  0  0] by nn
[9.9999893e-01 1.2103925e-09 1.4732427e-14 1.1044377e-06 2.9165391e-33]
[-1  0  0] by nn
[9.9999917e-01 1.8732098e-09 3.3013072e-14 8.8980437e-07 1.0348949e-32]
[-1  0  0] by nn
[9.9999821e-01 2.7321896e-09 1.4763562e-13 1.7377469e-06 2.8383910e-31]
[-1  0  0] by nn
[9.9999535e-01 6.8996795e-09 1.0309258e-12 4.6265022e-06 1.1189643e-29]
[-1  0  0] by nn
[9.9999452e-01 1.1679773e-08 3.9717830e-12 5.4257675e-06 1.2832558e-28]
[-1  0  0] by nn
[9.9999261e-01 2.6656087e-08 1.3934487e-11 7.3758274e-06 3.0711293e-27]
[-1  0  0] by nn
[9.9999070e-01 4.2607031e-08 5.6755219e-11 9.3323179e-06 1.0821871e-25]
[-1  0  0] by nn
[9.9998808e-01 6.1274555e-08 1.3837521e-10 1.1773072e-05 8.9428230e-25]
[-1  0  0] by nn
[9.9998617e-01 1.6045463e-07 8.5953583e-10 1.3747428e-05 3.1877102e-23]
[-1 

[9.9999833e-01 9.0186703e-08 6.0750370e-11 1.5012151e-06 1.2035242e-25]
[-1  0  0] by nn
[9.9999928e-01 3.0211094e-08 4.0321791e-12 7.6033990e-07 2.7765009e-27]
[-1  0  0] by nn
[9.9999905e-01 6.2782675e-08 2.1098793e-11 8.5828600e-07 1.4458210e-24]
[-1  0  0] by nn
[9.9999225e-01 1.2185528e-06 1.5696077e-09 6.5610575e-06 1.4697496e-18]
[-1  0  0] by nn
[9.9985552e-01 1.5568194e-05 2.8656951e-08 1.2877563e-04 4.5150572e-12]
[-1  0  0] by nn
[9.9821424e-01 1.5053333e-04 8.6348237e-08 1.6348275e-03 3.5732370e-07]
[-1  0  0] by nn
[9.9555004e-01 2.7297233e-04 4.2536379e-07 4.1024419e-03 7.4116673e-05]
[-1  0  0] by nn
[9.8834538e-01 7.1322458e-04 3.4134268e-06 8.5153664e-03 2.4225698e-03]
[-1  0  0] by nn
[9.8004454e-01 1.5632446e-03 9.6556454e-05 1.6157333e-02 2.1383113e-03]
[-1  0  0] by nn
[9.7004557e-01 2.2103626e-03 5.5411621e-04 2.6378129e-02 8.1186916e-04]
[-1  0  0] by nn
[9.2795926e-01 5.2870242e-03 7.1855477e-04 6.5046310e-02 9.8881265e-04]
[-1  0  0] by nn
[9.2262620e-01 1.0105

[-1  0  0] by nn
[9.8750311e-01 3.1268632e-03 5.6481058e-05 9.3083652e-03 5.1433235e-06]
[-1  0  0] by nn
[9.8881638e-01 2.8725401e-03 7.2457617e-05 8.2311435e-03 7.5069693e-06]
[-1  0  0] by nn
[9.8203045e-01 4.2344728e-03 1.0478541e-04 1.3617976e-02 1.2414694e-05]
[-1  0  0] by nn
[9.7774988e-01 5.1598833e-03 7.7138422e-05 1.6983705e-02 2.9419141e-05]
[-1  0  0] by nn
[9.6115762e-01 7.5205895e-03 6.5788103e-05 3.1209521e-02 4.6456957e-05]
[-1  0  0] by nn
[9.3584460e-01 1.0272225e-02 6.1421371e-05 5.3710829e-02 1.1089830e-04]
[-1  0  0] by nn
[8.8665104e-01 1.3706812e-02 7.8730365e-05 9.9381387e-02 1.8216159e-04]
[-1  0  0] by nn
[8.0809844e-01 1.8423377e-02 9.4943680e-05 1.7302549e-01 3.5776090e-04]
[-1  0  0] by nn
[6.4060688e-01 2.7157445e-02 1.0377825e-04 3.3140817e-01 7.2372111e-04]
[-1  0  0] by nn
[5.6888103e-01 3.8849350e-02 1.4051232e-04 3.9076498e-01 1.3641248e-03]
[-1  0  0] by nn
[5.0788987e-01 5.9556644e-02 1.5493097e-04 4.2941403e-01 2.9845317e-03]
[-1  0  0] by nn
[5.0

[0.06611697 0.16356051 0.36927554 0.1538294  0.24721758]
[0 1 0] by nn
[0.06279896 0.17305331 0.3571067  0.15412891 0.25291213]
[0 1 0] by nn
[0.06545973 0.17891446 0.35198763 0.16581437 0.23782384]
[0 1 0] by nn
[0.06091114 0.18909293 0.34760454 0.15908387 0.24330755]
[0 1 0] by nn
[0.05966878 0.19678679 0.33395782 0.15893479 0.25065178]
[0 1 0] by nn
[0.05575966 0.20829734 0.31942445 0.16362908 0.25288945]
[0 1 0] by nn
[0.06240319 0.22776185 0.29400656 0.16941799 0.24641035]
[0 1 0] by nn
[0.05814491 0.2377448  0.2658559  0.16418555 0.2740688 ]
[0 1 0] by nn
[0.05684019 0.2432909  0.25575957 0.1579277  0.2861816 ]
[0 1 0] by nn
[0.05152352 0.25245064 0.2545094  0.15284316 0.28867328]
[0 1 0] by nn
[0.04910585 0.26048923 0.23615581 0.15934673 0.29490238]
[1 0 0] by nn
[0.05751051 0.34012204 0.13085178 0.15776554 0.31375018]
[1 0 0] by nn
[0.05886422 0.27873293 0.15189803 0.14149345 0.3690114 ]
[1 0 0] by nn
[0.06954575 0.23570046 0.15523121 0.13205136 0.40747124]
[1 0 0] by nn
[0.074

[0.20836553 0.24726342 0.11572911 0.26496702 0.16367494]
[1 0 0] by nn
[0.290992   0.16018136 0.09992    0.24149089 0.20741582]
[0 1 0] by nn
[0.4229044  0.08970969 0.07027934 0.22268207 0.19442447]
[-1  0  0] by nn
[0.5156706  0.05381577 0.06917971 0.20094512 0.16038878]
[-1  0  0] by nn
[0.6536013  0.03649565 0.05302017 0.15058286 0.10630006]
[-1  0  0] by nn
[0.76346684 0.02557224 0.01686742 0.14150022 0.05259317]
[-1  0  0] by nn
[0.82485074 0.01752684 0.00876109 0.12071754 0.02814388]
[-1  0  0] by nn
[0.9293077  0.0081739  0.0011789  0.05875862 0.00258082]
[-1  0  0] by nn
[9.6008092e-01 1.7190243e-03 2.2616047e-04 3.7965581e-02 8.3683726e-06]
[-1  0  0] by nn
[9.9926537e-01 1.0080717e-05 3.4200443e-08 7.2446134e-04 5.3723848e-15]
[-1  0  0] by nn
[9.9994206e-01 2.1019069e-07 2.4780045e-10 5.7693767e-05 1.0495748e-22]
[-1  0  0] by nn
[9.9999619e-01 4.2661807e-09 5.6871990e-12 3.8405815e-06 5.2380293e-29]
[-1  0  0] by nn
[9.9999785e-01 1.3359482e-09 7.9790983e-12 2.1216517e-06 7

[1.4745379e-02 8.5907966e-01 5.6224276e-04 6.9680542e-02 5.5932172e-02]
[1 0 0] by nn
[1.2799268e-02 8.7797201e-01 3.2737307e-04 5.8580495e-02 5.0320886e-02]
[1 0 0] by nn
[1.2157428e-02 8.7382978e-01 2.7489912e-04 5.9747756e-02 5.3990107e-02]
[1 0 0] by nn
[1.2219542e-02 9.0016913e-01 4.2806519e-04 5.7020739e-02 3.0162495e-02]
[1 0 0] by nn
[2.2992611e-02 8.8583046e-01 6.0037768e-04 6.4942375e-02 2.5634136e-02]
[1 0 0] by nn
[0.04300876 0.85957754 0.00088455 0.06796221 0.02856688]
[1 0 0] by nn
[0.0529312  0.83295906 0.0025872  0.08302383 0.02849874]
[1 0 0] by nn
[0.08446708 0.7646777  0.00788088 0.11256807 0.0304062 ]
[1 0 0] by nn
[0.08427968 0.70925003 0.01959002 0.14325655 0.04362373]
[1 0 0] by nn
[0.07704066 0.67279327 0.03934269 0.15463495 0.05618841]
[1 0 0] by nn
[0.07544699 0.5902097  0.09068528 0.16256149 0.08109649]
[1 0 0] by nn
[0.08737537 0.44368657 0.19241661 0.1677767  0.10874472]
[1 0 0] by nn
[0.09593827 0.31860805 0.30348286 0.15819584 0.12377504]
[1 0 0] by nn
[0

[0.81500876 0.01325692 0.01142463 0.03747089 0.12283883]
[-1  0  0] by nn
[0.7951415  0.01627326 0.01551759 0.04235884 0.13070883]
[-1  0  0] by nn
[0.75668246 0.02052744 0.02536526 0.05069773 0.14672713]
[-1  0  0] by nn
[0.690481   0.03599114 0.0558567  0.06597885 0.15169229]
[-1  0  0] by nn
[0.4973318  0.07957914 0.13699481 0.11318792 0.17290635]
[-1  0  0] by nn
[0.33409604 0.11281548 0.22398704 0.14928827 0.17981318]
[0 1 0] by nn
[0.13977264 0.22745952 0.2519199  0.16786113 0.21298677]
[0 1 0] by nn
[0.06523924 0.38934723 0.17121136 0.14176828 0.23243393]
[1 0 0] by nn
[0.04124818 0.5476176  0.08455651 0.13041031 0.1961673 ]
[1 0 0] by nn
[0.0373527  0.6339395  0.04146751 0.11352365 0.17371656]
[1 0 0] by nn
[0.04096549 0.638794   0.02810546 0.13489051 0.15724452]
[1 0 0] by nn
[0.04366595 0.67700464 0.0176522  0.12380395 0.13787323]
[1 0 0] by nn
[0.03327972 0.65007293 0.02721954 0.13805348 0.15137431]
[1 0 0] by nn
[0.04044018 0.6682247  0.01763159 0.12764513 0.1460584 ]
[1 0 

[0.07371554 0.14420147 0.3729839  0.13826424 0.2708349 ]
[0 1 0] by nn
[0.07276086 0.14629115 0.36276856 0.13984732 0.27833202]
[0 1 0] by nn
[0.07015472 0.14789176 0.3582009  0.13930881 0.2844438 ]
[0 1 0] by nn
[0.06901155 0.15195058 0.35572743 0.14028922 0.28302115]
[0 1 0] by nn
[0.06958621 0.15236953 0.35374823 0.13836625 0.2859297 ]
[0 1 0] by nn
[0.06512786 0.15999588 0.3481007  0.13790645 0.28886908]
[0 1 0] by nn
[0.06338721 0.16127677 0.34606594 0.1387678  0.29050228]
[0 1 0] by nn
[0.06143756 0.16332066 0.33601013 0.14106734 0.29816434]
[0 1 0] by nn
[0.06170825 0.16577777 0.32586455 0.14327818 0.30337116]
[0 1 0] by nn
[0.06165192 0.16876452 0.3152308  0.14661536 0.3077374 ]
[0 1 0] by nn
[0.06217073 0.16633777 0.3134308  0.14766613 0.3103946 ]
[0 1 0] by nn
[0.06007811 0.16860339 0.3114254  0.1453372  0.31455594]
[0 1 0] by nn
[0.06023445 0.16472429 0.35851413 0.14684112 0.26968598]
[0 1 0] by nn
[0.06013959 0.16541249 0.35461184 0.14639731 0.27343878]
[0 1 0] by nn
[0.056

[9.9999928e-01 3.7340446e-09 3.5205501e-14 6.6756888e-07 6.7322160e-32]
[-1  0  0] by nn
[9.9999881e-01 3.6492553e-09 1.5856313e-14 1.2397031e-06 2.9735434e-31]
[-1  0  0] by nn
[9.9999869e-01 2.7245881e-09 7.8025431e-15 1.2949214e-06 1.2674581e-30]
[-1  0  0] by nn
[9.9999607e-01 7.8532043e-09 3.7388122e-14 3.9071933e-06 1.9581905e-28]
[-1  0  0] by nn
[9.9998879e-01 2.6416332e-08 5.3177298e-13 1.1186964e-05 5.8713229e-24]
[-1  0  0] by nn
[9.99877453e-01 1.12193345e-06 3.15111631e-10 1.21501784e-04
 2.47253947e-16]
[-1  0  0] by nn
[9.9738818e-01 1.1874110e-04 1.2377350e-06 2.4913785e-03 4.9437040e-07]
[-1  0  0] by nn
[9.7989619e-01 1.7277895e-03 2.2441748e-04 1.2276699e-02 5.8749770e-03]
[-1  0  0] by nn
[9.6137726e-01 1.4587924e-03 5.2629033e-04 1.0918580e-02 2.5719006e-02]
[-1  0  0] by nn
[0.9350458  0.00299884 0.0013343  0.0153277  0.04529335]
[-1  0  0] by nn
[0.9027995  0.00764885 0.00428117 0.02533623 0.05993426]
[-1  0  0] by nn
[0.8306574  0.01557899 0.01770294 0.0368256  

[0.7544325  0.01643112 0.01746249 0.04688433 0.16478953]
[-1  0  0] by nn
[0.71765757 0.01681278 0.02693695 0.06006031 0.17853247]
[-1  0  0] by nn
[0.82000864 0.01142725 0.01035723 0.04049949 0.11770737]
[-1  0  0] by nn
[0.7846058  0.0144779  0.01508733 0.04978369 0.13604529]
[-1  0  0] by nn
[0.8118918  0.01487595 0.01126305 0.04119741 0.12077179]
[-1  0  0] by nn
[0.7741051  0.01794604 0.0180268  0.04359104 0.14633101]
[-1  0  0] by nn
[0.71311957 0.02659435 0.03476906 0.05455663 0.17096043]
[-1  0  0] by nn
[0.61291367 0.05289044 0.08297107 0.07553514 0.17568968]
[-1  0  0] by nn
[0.4258899  0.09878718 0.16110985 0.12067115 0.19354193]
[-1  0  0] by nn
[0.24665888 0.15534374 0.22607327 0.16875379 0.20317036]
[0 1 0] by nn
[0.10164798 0.29877442 0.20788887 0.17215542 0.2195333 ]
[1 0 0] by nn
[0.05099376 0.44706896 0.13334964 0.14079069 0.22779694]
[1 0 0] by nn
[0.0347794  0.60253793 0.04865043 0.12615252 0.1878797 ]
[1 0 0] by nn
[0.02996707 0.69644964 0.02296994 0.10990281 0.140

[0.16886438 0.08719984 0.26660076 0.11080622 0.3665288 ]
[0 1 0] by nn
[0.34930182 0.04913322 0.21121742 0.07855976 0.31178784]
[0 1 0] by nn
[0.5831918  0.02839188 0.09808008 0.05823003 0.23210615]
[-1  0  0] by nn
[0.7786044  0.01708515 0.03148974 0.03983508 0.13298559]
[-1  0  0] by nn
[0.8335941  0.01342966 0.01852638 0.03919064 0.09525927]
[-1  0  0] by nn
[0.8859066  0.01105773 0.00899188 0.03133776 0.06270607]
[-1  0  0] by nn
[0.84318227 0.01468409 0.01537462 0.05226012 0.07449897]
[-1  0  0] by nn
[0.88672674 0.01165189 0.00779283 0.03769282 0.05613574]
[-1  0  0] by nn
[0.8656574  0.01146417 0.01236693 0.04157738 0.06893403]
[-1  0  0] by nn
[0.8563863  0.01434232 0.01681614 0.03385364 0.07860167]
[-1  0  0] by nn
[0.7529292  0.02501334 0.04887433 0.05070679 0.12247629]
[-1  0  0] by nn
[0.62473387 0.04054553 0.12632199 0.07219352 0.13620506]
[-1  0  0] by nn
[0.42210442 0.07316413 0.23347373 0.09438805 0.17686965]
[-1  0  0] by nn
[0.23471676 0.13100186 0.32057044 0.13604689

[0.7787743  0.01116031 0.01851054 0.0491859  0.14236893]
[-1  0  0] by nn
[0.7869052  0.01056559 0.01797989 0.04603914 0.13851015]
[-1  0  0] by nn
[0.7969372  0.01103951 0.01474757 0.03675172 0.14052388]
[-1  0  0] by nn
[0.7681217  0.01371708 0.02043916 0.04275463 0.1549675 ]
[-1  0  0] by nn
[0.7551098  0.01601921 0.02731626 0.04652025 0.15503453]
[-1  0  0] by nn
[0.72231126 0.02448708 0.04257542 0.05941186 0.1512144 ]
[-1  0  0] by nn
[0.6125436  0.04578932 0.09430885 0.08289099 0.1644672 ]
[-1  0  0] by nn
[0.3978354  0.07963063 0.18777578 0.13207375 0.20268449]
[-1  0  0] by nn
[0.23117937 0.13301232 0.25427246 0.16902296 0.2125129 ]
[0 1 0] by nn
[0.11594921 0.28508222 0.21797347 0.17555167 0.20544343]
[1 0 0] by nn
[0.05898601 0.44991153 0.13203116 0.14289458 0.21617667]
[1 0 0] by nn
[0.04131783 0.6374269  0.04338521 0.12076625 0.15710384]
[1 0 0] by nn
[0.0356374  0.72181773 0.01663716 0.10184792 0.12405973]
[1 0 0] by nn
[0.04571644 0.73258615 0.01167799 0.12144604 0.088573

[0.07318929 0.60136646 0.03413403 0.17450172 0.11680857]
[1 0 0] by nn
[0.06831531 0.5593338  0.06785361 0.16091496 0.1435823 ]
[1 0 0] by nn
[0.06665406 0.47600833 0.13258955 0.15734436 0.16740379]
[1 0 0] by nn
[0.06494305 0.33918464 0.28183112 0.13559783 0.17844339]
[1 0 0] by nn
[0.06743214 0.2004956  0.42644516 0.12062289 0.18500416]
[0 1 0] by nn
[0.08595527 0.12498911 0.4384973  0.10996143 0.24059686]
[0 1 0] by nn
[0.13915582 0.0890336  0.33505568 0.10692564 0.3298292 ]
[0 1 0] by nn
[0.22640263 0.06588335 0.16440909 0.09798465 0.4453203 ]
[0 1 0] by nn
[0.41622278 0.04879414 0.09976231 0.09674364 0.33847713]
[-1  0  0] by nn
[0.5737978  0.02751985 0.04929705 0.07191629 0.277469  ]
[-1  0  0] by nn
[0.71519685 0.01718149 0.02353876 0.05661737 0.18746561]
[-1  0  0] by nn
[0.7220786  0.01303429 0.02736951 0.06464468 0.17287299]
[-1  0  0] by nn
[0.82574916 0.00774405 0.00948008 0.03912932 0.11789749]
[-1  0  0] by nn
[0.8150768  0.00687085 0.01028791 0.03836518 0.1293992 ]
[-1  

[-1  0  0] by nn
[0.77687144 0.01080343 0.01763617 0.05199263 0.14269637]
[-1  0  0] by nn
[0.8599851  0.00693416 0.00624186 0.03552591 0.09131294]
[-1  0  0] by nn
[0.8355955  0.00800347 0.00810564 0.04082046 0.10747498]
[-1  0  0] by nn
[0.8479979  0.00965282 0.00924873 0.0334785  0.09962213]
[-1  0  0] by nn
[0.79254234 0.01685486 0.0224692  0.04196725 0.12616634]
[-1  0  0] by nn
[0.7021247  0.02703572 0.0480346  0.05929477 0.16351014]
[-1  0  0] by nn
[0.5343851  0.06114472 0.08987717 0.09712455 0.21746847]
[-1  0  0] by nn
[0.37127545 0.09759084 0.10331158 0.15164201 0.27618015]
[-1  0  0] by nn
[0.17882092 0.18033352 0.097531   0.17626485 0.36704972]
[0 1 0] by nn
[0.07462789 0.28636497 0.09980275 0.15581815 0.38338622]
[1 0 0] by nn
[0.03456026 0.52235717 0.06199531 0.09397133 0.287116  ]
[1 0 0] by nn
[0.02357796 0.705096   0.02996229 0.06377774 0.17758599]
[1 0 0] by nn
[0.02524327 0.7467522  0.01584552 0.05452283 0.1576362 ]
[1 0 0] by nn
[0.02626637 0.8024891  0.00546174 0.

[9.6783489e-01 3.0506959e-03 1.4231120e-04 2.4037153e-02 4.9349852e-03]
[-1  0  0] by nn
[9.8731470e-01 1.1569614e-03 4.5057943e-05 1.0779069e-02 7.0419291e-04]
[-1  0  0] by nn
[9.9593461e-01 3.3341927e-04 1.1304121e-05 3.6935867e-03 2.7048576e-05]
[-1  0  0] by nn
[9.9787617e-01 1.4556208e-04 2.6258233e-06 1.9747878e-03 7.8406913e-07]
[-1  0  0] by nn
[9.9849451e-01 6.6091183e-05 1.3901511e-06 1.4379924e-03 3.8423881e-08]
[-1  0  0] by nn
[9.9895275e-01 3.8555831e-05 4.7448140e-07 1.0081581e-03 4.3222834e-09]
[-1  0  0] by nn
[9.9923599e-01 1.9244973e-05 1.3884404e-07 7.4464577e-04 2.1069521e-10]
[-1  0  0] by nn
[9.9938297e-01 1.7381286e-05 8.2882437e-08 5.9955113e-04 3.0915853e-11]
[-1  0  0] by nn
[9.9967921e-01 1.0967998e-05 4.7536261e-08 3.0973944e-04 2.9221178e-12]
[-1  0  0] by nn
[9.9961424e-01 8.0192931e-06 3.9538513e-08 3.7769429e-04 1.1322464e-12]
[-1  0  0] by nn
[9.9955529e-01 7.7375471e-06 3.6097529e-08 4.3695056e-04 7.1675446e-13]
[-1  0  0] by nn
[9.9948251e-01 1.3203

[0.03435598 0.5657004  0.05533129 0.11606744 0.2285449 ]
[1 0 0] by nn
[0.04183191 0.4425594  0.12341883 0.13043499 0.26175484]
[1 0 0] by nn
[0.05435699 0.28314924 0.21570206 0.13760377 0.30918786]
[1 0 0] by nn
[0.07309133 0.15936437 0.32475618 0.12928094 0.31350717]
[0 1 0] by nn
[0.13243373 0.1058768  0.32394415 0.12817052 0.30957472]
[0 1 0] by nn
[0.25794902 0.068848   0.23074797 0.1023083  0.34014675]
[0 1 0] by nn
[0.53367084 0.0371601  0.0781789  0.07557587 0.27541432]
[-1  0  0] by nn
[0.7538112  0.01899903 0.02079141 0.05035184 0.15604657]
[-1  0  0] by nn
[0.83082604 0.00986425 0.00917807 0.04189049 0.10824123]
[-1  0  0] by nn
[0.8910682  0.00573266 0.00370155 0.03678323 0.06271435]
[-1  0  0] by nn
[0.8861585  0.00544026 0.00508545 0.04323677 0.06007897]
[-1  0  0] by nn
[0.9298783  0.00344023 0.00169013 0.02805484 0.03693653]
[-1  0  0] by nn
[0.92025536 0.00341354 0.00205593 0.03059831 0.04367692]
[-1  0  0] by nn
[0.9362749  0.00391593 0.00147588 0.02140385 0.03692956]

[0.0665644  0.14134759 0.29729402 0.14092703 0.353867  ]
[0 1 0] by nn
[0.06612199 0.13853094 0.30485106 0.14928368 0.34121227]
[0 1 0] by nn
[0.07009409 0.13902092 0.27992472 0.15239418 0.35856614]
[0 1 0] by nn
[0.07114664 0.14036728 0.27020738 0.15524094 0.36303774]
[0 1 0] by nn
[0.07189021 0.14524105 0.2634824  0.15632845 0.36305788]
[0 1 0] by nn
[0.07022947 0.14766188 0.25845766 0.15764749 0.36600348]
[0 1 0] by nn
[0.07126221 0.14756852 0.2587907  0.15738904 0.36498952]
[0 1 0] by nn
[0.06918173 0.14887576 0.26753092 0.1641624  0.3502492 ]
[0 1 0] by nn
[0.07289764 0.15220329 0.25777885 0.1658499  0.35127035]
[0 1 0] by nn
[0.07145862 0.15443052 0.24769038 0.16846581 0.35795468]
[0 1 0] by nn
[0.0704303  0.15603937 0.24444708 0.16995376 0.35912955]
[0 1 0] by nn
[0.07111514 0.1574451  0.24158831 0.17093502 0.3589164 ]
[0 1 0] by nn
[0.06951075 0.15868662 0.23951142 0.17006463 0.3622266 ]
[0 1 0] by nn
[0.07096302 0.15887487 0.22792394 0.16521837 0.37701982]
[0 1 0] by nn
[0.070

[0.7543847  0.0090481  0.00678647 0.15556578 0.07421492]
[-1  0  0] by nn
[0.661747   0.00486551 0.00562015 0.1236563  0.20411116]
[-1  0  0] by nn
[8.7303150e-01 2.2823764e-03 6.8304135e-04 5.9093259e-02 6.4909928e-02]
[-1  0  0] by nn
[8.9724833e-01 1.8486459e-03 5.3874671e-04 5.6195952e-02 4.4168405e-02]
[-1  0  0] by nn
[9.4632190e-01 1.1140070e-03 1.9546201e-04 3.4199417e-02 1.8169245e-02]
[-1  0  0] by nn
[9.7772038e-01 6.0426939e-04 1.4700544e-04 1.8218892e-02 3.3095349e-03]
[-1  0  0] by nn
[9.8988616e-01 4.0828422e-04 8.4911706e-05 9.0598008e-03 5.6081265e-04]
[-1  0  0] by nn
[9.952865e-01 1.949940e-04 2.618166e-05 4.456550e-03 3.579066e-05]
[-1  0  0] by nn
[9.9636590e-01 1.8615914e-04 1.5563071e-05 3.4202277e-03 1.2142920e-05]
[-1  0  0] by nn
[9.97681499e-01 1.15051997e-04 1.09707435e-05 2.18182639e-03
 1.07395963e-05]
[-1  0  0] by nn
[9.9802423e-01 1.2392284e-04 1.6639129e-05 1.8316008e-03 3.5655944e-06]
[-1  0  0] by nn
[9.9702340e-01 1.7937127e-04 2.8203094e-05 2.76431

[-1  0  0] by nn
[9.9505758e-01 4.4512481e-04 1.2727469e-07 4.4970661e-03 8.3160748e-17]
[-1  0  0] by nn
[9.7805119e-01 5.7443744e-03 6.4162492e-08 1.6204398e-02 3.2704332e-14]
[-1  0  0] by nn
[9.2809170e-01 6.0054455e-02 3.1132890e-07 1.1853482e-02 4.7668897e-10]
[-1  0  0] by nn
[0.5514677  0.28015882 0.00097666 0.16619824 0.00119855]
[-1  0  0] by nn
[6.0030365e-01 3.0834815e-01 2.3906498e-04 7.7766597e-02 1.3342448e-02]
[-1  0  0] by nn
[0.4973471  0.30889022 0.00117295 0.10584915 0.08674064]
[-1  0  0] by nn
[0.46782017 0.26420838 0.00231463 0.08471271 0.18094414]
[-1  0  0] by nn
[0.40916303 0.2261634  0.01524456 0.12070385 0.22872517]
[-1  0  0] by nn
[0.24099863 0.29379398 0.07176523 0.13034004 0.26310217]
[1 0 0] by nn
[0.04300824 0.44500068 0.06871975 0.13538694 0.30788442]
[1 0 0] by nn
[0.00866248 0.63113546 0.01565566 0.09003348 0.25451282]
[1 0 0] by nn
[0.00375411 0.6733206  0.00152619 0.11927481 0.20212428]
[1 0 0] by nn
[7.8537193e-04 8.1631351e-01 3.4643046e-04 1.30

[0.  0.  0.8] by nn
[0.07039537 0.2626495  0.02408114 0.6153241  0.0275499 ]
[0.  0.  0.8] by nn
[0.07379735 0.2489778  0.03118294 0.6180795  0.02796249]
[0.  0.  0.8] by nn
[0.07379735 0.2489778  0.03118294 0.6180795  0.02796249]
[0.  0.  0.8] by nn
[0.07379735 0.2489778  0.03118294 0.6180795  0.02796249]
[0.  0.  0.8] by nn
[0.07379735 0.2489778  0.03118294 0.6180795  0.02796249]
[0.  0.  0.8] by nn
[0.07379735 0.2489778  0.03118294 0.6180795  0.02796249]
[0.  0.  0.8] by nn
[0.07379735 0.2489778  0.03118294 0.6180795  0.02796249]
[0.  0.  0.8] by nn
[0.07379735 0.2489778  0.03118294 0.6180795  0.02796249]
[0.  0.  0.8] by nn
[0.07379735 0.2489778  0.03118294 0.6180795  0.02796249]
[0.  0.  0.8] by nn
[0.07379735 0.2489778  0.03118294 0.6180795  0.02796249]
[0.  0.  0.8] by nn
[0.07379735 0.2489778  0.03118294 0.6180795  0.02796249]
[0.  0.  0.8] by nn
[0.09256356 0.31751257 0.02615895 0.53551483 0.02825005]
[0.  0.  0.8] by nn
[0.09256356 0.31751257 0.02615895 0.53551483 0.02825005]

[0.08919033 0.31526783 0.02715745 0.5404071  0.02797727]
[0.  0.  0.8] by nn
[0.08919033 0.31526783 0.02715745 0.5404071  0.02797727]
[0.  0.  0.8] by nn
[0.08919033 0.31526783 0.02715745 0.5404071  0.02797727]
[0.  0.  0.8] by nn
[0.08919033 0.31526783 0.02715745 0.5404071  0.02797727]
[0.  0.  0.8] by nn
[0.08919033 0.31526783 0.02715745 0.5404071  0.02797727]
[0.  0.  0.8] by nn
[0.07871284 0.27849683 0.02830895 0.58581    0.02867141]
[0.  0.  0.8] by nn
[0.07871284 0.27849683 0.02830895 0.58581    0.02867141]
[0.  0.  0.8] by nn
[0.07871284 0.27849683 0.02830895 0.58581    0.02867141]
[0.  0.  0.8] by nn
[0.07871284 0.27849683 0.02830895 0.58581    0.02867141]
[0.  0.  0.8] by nn
[0.07871284 0.27849683 0.02830895 0.58581    0.02867141]
[0.  0.  0.8] by nn
[0.07871284 0.27849683 0.02830895 0.58581    0.02867141]
[0.  0.  0.8] by nn
[0.07871284 0.27849683 0.02830895 0.58581    0.02867141]
[0.  0.  0.8] by nn
[0.07871284 0.27849683 0.02830895 0.58581    0.02867141]
[0.  0.  0.8] by nn

[0.07691409 0.28915945 0.02857344 0.576145   0.02920802]
[0.  0.  0.8] by nn
[0.07691409 0.28915945 0.02857344 0.576145   0.02920802]
[0.  0.  0.8] by nn
[0.07691409 0.28915945 0.02857344 0.576145   0.02920802]
[0.  0.  0.8] by nn
[0.07691409 0.28915945 0.02857344 0.576145   0.02920802]
[0.  0.  0.8] by nn
[0.07691409 0.28915945 0.02857344 0.576145   0.02920802]
[0.  0.  0.8] by nn
[0.07691409 0.28915945 0.02857344 0.576145   0.02920802]
[0.  0.  0.8] by nn
[0.07691409 0.28915945 0.02857344 0.576145   0.02920802]
[0.  0.  0.8] by nn
[0.07691409 0.28915945 0.02857344 0.576145   0.02920802]
[0.  0.  0.8] by nn
[0.07691409 0.28915945 0.02857344 0.576145   0.02920802]
[0.  0.  0.8] by nn
[0.08577374 0.260503   0.03187441 0.5957328  0.02611604]
[0.  0.  0.8] by nn
[0.08577374 0.260503   0.03187441 0.5957328  0.02611604]
[0.  0.  0.8] by nn
[0.08577374 0.260503   0.03187441 0.5957328  0.02611604]
[0.  0.  0.8] by nn
[0.08577374 0.260503   0.03187441 0.5957328  0.02611604]
[0.  0.  0.8] by nn

[0.09301588 0.3041357  0.02999867 0.5479954  0.02485436]
[0.  0.  0.8] by nn
[0.09301588 0.3041357  0.02999867 0.5479954  0.02485436]
[0.  0.  0.8] by nn
[0.09301588 0.3041357  0.02999867 0.5479954  0.02485436]
[0.  0.  0.8] by nn
[0.08561901 0.31074452 0.0296862  0.5492497  0.02470057]
[0.  0.  0.8] by nn
[0.08561901 0.31074452 0.0296862  0.5492497  0.02470057]
[0.  0.  0.8] by nn
[0.08561901 0.31074452 0.0296862  0.5492497  0.02470057]
[0.  0.  0.8] by nn
[0.08561901 0.31074452 0.0296862  0.5492497  0.02470057]
[0.  0.  0.8] by nn
[0.08561901 0.31074452 0.0296862  0.5492497  0.02470057]
[0.  0.  0.8] by nn
[0.08561901 0.31074452 0.0296862  0.5492497  0.02470057]
[0.  0.  0.8] by nn
[0.08561901 0.31074452 0.0296862  0.5492497  0.02470057]
[0.  0.  0.8] by nn
[0.08561901 0.31074452 0.0296862  0.5492497  0.02470057]
[0.  0.  0.8] by nn
[0.08561901 0.31074452 0.0296862  0.5492497  0.02470057]
[0.  0.  0.8] by nn
[0.08561901 0.31074452 0.0296862  0.5492497  0.02470057]
[0.  0.  0.8] by nn

[0.08285601 0.28504258 0.03009192 0.5736594  0.02835007]
[0.  0.  0.8] by nn
[0.08285601 0.28504258 0.03009192 0.5736594  0.02835007]
[0.  0.  0.8] by nn
[0.08285601 0.28504258 0.03009192 0.5736594  0.02835007]
[0.  0.  0.8] by nn
[0.08285601 0.28504258 0.03009192 0.5736594  0.02835007]
[0.  0.  0.8] by nn
[0.08285601 0.28504258 0.03009192 0.5736594  0.02835007]
[0.  0.  0.8] by nn
[0.08285601 0.28504258 0.03009192 0.5736594  0.02835007]
[0.  0.  0.8] by nn
[0.08285601 0.28504258 0.03009192 0.5736594  0.02835007]
[0.  0.  0.8] by nn
[0.09001426 0.28628686 0.02949947 0.56548476 0.02871464]
[0.  0.  0.8] by nn
[0.09001426 0.28628686 0.02949947 0.56548476 0.02871464]
[0.  0.  0.8] by nn
[0.09001426 0.28628686 0.02949947 0.56548476 0.02871464]
[0.  0.  0.8] by nn
[0.09001426 0.28628686 0.02949947 0.56548476 0.02871464]
[0.  0.  0.8] by nn
[0.09001426 0.28628686 0.02949947 0.56548476 0.02871464]
[0.  0.  0.8] by nn
[0.09001426 0.28628686 0.02949947 0.56548476 0.02871464]
[0.  0.  0.8] by nn

[0.09551281 0.29988375 0.02688364 0.5485736  0.02914617]
[0.  0.  0.8] by nn
[0.07562865 0.28246102 0.0215372  0.58991504 0.03045811]
[0.  0.  0.8] by nn
[0.07562865 0.28246102 0.0215372  0.58991504 0.03045811]
[0.  0.  0.8] by nn
[0.07562865 0.28246102 0.0215372  0.58991504 0.03045811]
[0.  0.  0.8] by nn
[0.07562865 0.28246102 0.0215372  0.58991504 0.03045811]
[0.  0.  0.8] by nn
[0.07562865 0.28246102 0.0215372  0.58991504 0.03045811]
[0.  0.  0.8] by nn
[0.07562865 0.28246102 0.0215372  0.58991504 0.03045811]
[0.  0.  0.8] by nn
[0.07562865 0.28246102 0.0215372  0.58991504 0.03045811]
[0.  0.  0.8] by nn
[0.07562865 0.28246102 0.0215372  0.58991504 0.03045811]
[0.  0.  0.8] by nn
[0.07562865 0.28246102 0.0215372  0.58991504 0.03045811]
[0.  0.  0.8] by nn
[0.07562865 0.28246102 0.0215372  0.58991504 0.03045811]
[0.  0.  0.8] by nn
[0.08896209 0.29093382 0.02603848 0.56509334 0.0289723 ]
[0.  0.  0.8] by nn
[0.08896209 0.29093382 0.02603848 0.56509334 0.0289723 ]
[0.  0.  0.8] by nn