In [40]:
# Importing Dependencies
import numpy as np
import gym
from gym.envs.box2d.car_racing import *
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPool2D, BatchNormalization
from keras.optimizers import Adam
from statistics import mean
from pyglet.window import key
import time
from tqdm import tqdm 
import os
from keras.utils import normalize

In [2]:
# Function for generating data by playing
def start_playing(n_episodes):
    a = np.array( [0.0, 0.0, 0.0] )
    def key_press(k, mod):
        global restart
        if k==0xff0d: restart = True
        if k==key.LEFT:  a[0] = -1.0
        if k==key.RIGHT: a[0] = +1.0
        if k==key.UP:    a[1] = +1.0
        if k==key.DOWN:  a[2] = +0.8   
    def key_release(k, mod):
        if k==key.LEFT  and a[0]==-1.0: a[0] = 0
        if k==key.RIGHT and a[0]==+1.0: a[0] = 0
        if k==key.UP:    a[1] = 0
        if k==key.DOWN:  a[2] = 0
    
    env = CarRacing()
    env.render()
    env.viewer.window.on_key_press = key_press
    env.viewer.window.on_key_release = key_release
    
    for episode in range(n_episodes):
        prev_observation = env.reset()
        if episode==0:
            X = np.array(prev_observation.tolist())
            y = np.array([0.,0.,0.])
        restart = False
        while True:
            action = a
            observation, reward, done, info = env.step(action)
            X = np.vstack((X, prev_observation))
            y = np.vstack((y, action))
            prev_observation=observation
            env.render()
            if done or restart: break
        time.sleep(2)    
    np.save('train_X.npy', X)
    np.save('train_y.npy', y)    
    env.close()
    return X, y

In [3]:
# Playing the to create data
X, y=start_playing(20)

Track generation: 1121..1405 -> 284-tiles track
Track generation: 925..1162 -> 237-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1228..1538 -> 310-tiles track
Track generation: 1132..1419 -> 287-tiles track
Track generation: 1282..1607 -> 325-tiles track
Track generation: 1171..1472 -> 301-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1120..1404 -> 284-tiles track
Track generation: 1030..1291 -> 261-tiles track
Track generation: 1119..1403 -> 284-tiles track
Track generation: 1126..1412 -> 286-tiles track
Track generation: 1413..1770 -> 357-tiles track
Track generation: 1230..1541 -> 311-tiles track
Track generation: 1246..1562 -> 316-tiles track
Track generation: 1128..1414 -> 286-tiles track
Track generation: 1085..1365 -> 280-tiles track
Track generation: 1387..1738 -> 351-tiles track
Track generation: 992..1251 -> 259-tiles track
Track generation: 1029..1296 -> 267-tiles 

In [8]:
# Combining gameplay files
temp = np.load('train_data-549.4999999999591.npy')
tempX = [i[0] for i in temp]
tempy = [i[1] for i in temp]
X = np.array(tempX)
y = np.array(tempy)
for file in tqdm(os.listdir('Data/')):
    temp = np.load('Data/' + file)
    tempX = [i[0] for i in temp]
    tempy = [i[1] for i in temp]
    tempX = np.array(tempX)
    tempy = np.array(tempy)
    X  = np.concatenate([X, tempX], axis=0)
    y  = np.concatenate([y, tempy], axis=0)

np.save('X.npy', X)    

100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:05<00:00,  1.60it/s]


In [5]:
# Converting output to proper OneHot array
Y=[]
for i in range(len(y)):  
    if np.array_equal(y[i], np.array([0,1,0])):
        Y.append(np.array([0,0,1,0,0]))
    elif np.array_equal(y[i], np.array([0,0,0.8])):
        Y.append(np.array([0,0,0,1,0]))
    elif np.array_equal(y[i], np.array([1,0,0])):
        Y.append(np.array([0,1,0,0,0]))
    elif np.array_equal(y[i], np.array([-1,0,0])):
        Y.append(np.array([1,0,0,0,0]))
    else:
        Y.append(np.array([0,0,0,0,1]))      
      
np.save('y_modified.npy', Y)    

In [41]:
# Loading the data
X = np.load('train_X.npy')
y = np.load('y_modified.npy')
X = X.reshape(-1,96,96,3)
print(X.shape)
print(y.shape)

(20450, 96, 96, 3)
(20450, 5)


In [23]:
# Variation in generated data
left=np.array([1,0,0,0,0])
right=np.array([0,1,0,0,0])
straight=np.array([0,0,1,0,0])
stop=np.array([0,0,0,1,0])
no_key=np.array([0,0,0,0,1])
l=0
r=0
s=0
b=0
nk=0

for key in y:
    if np.array_equal(key, left):
        l+=1
    elif np.array_equal(key, right):
        r+=1
    elif np.array_equal(key, straight):
        s+=1
    elif np.array_equal(key, stop):
        b+=1
    elif np.array_equal(key, no_key):
        nk+=1    
      
print(l,r,s,b,nk)    

2694 1318 4443 179 11816


In [56]:
model = Sequential()

model.add(Conv2D(filters = 16, kernel_size = (5,5),padding = 'Same', 
                 activation ='relu', input_shape = (96,96,3)))
model.add(Conv2D(filters = 16, kernel_size = (5,5),padding = 'Same', 
                 activation ='relu'))
model.add(BatchNormalization())
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Dropout(0.5))

model.add(Conv2D(filters = 32, kernel_size = (3,3),padding = 'Same', 
                 activation ='relu'))
model.add(Conv2D(filters = 32, kernel_size = (3,3),padding = 'Same', 
                 activation ='relu'))
model.add(BatchNormalization())
model.add(MaxPool2D(pool_size=(2,2), strides=(2,2)))
model.add(Dropout(0.5))


model.add(Flatten())
model.add(Dense(256, activation = "relu"))
model.add(BatchNormalization())
model.add(Dropout(0.5))

model.add(Dense(5, activation = "softmax"))

In [57]:
optimizer = Adam(lr=0.0001)
model.compile(optimizer = optimizer, loss = "categorical_crossentropy")

In [58]:
model.fit(X, y, epochs=10, validation_split=0.2, batch_size=600, verbose=1, shuffle=True)

Train on 16360 samples, validate on 4090 samples
Epoch 1/10
16360/16360 [==============================] - ETA: 53s - loss: 2.71 - ETA: 29s - loss: 2.62 - ETA: 21s - loss: 2.62 - ETA: 17s - loss: 2.57 - ETA: 14s - loss: 2.52 - ETA: 13s - loss: 2.52 - ETA: 11s - loss: 2.51 - ETA: 10s - loss: 2.49 - ETA: 9s - loss: 2.4639 - ETA: 8s - loss: 2.445 - ETA: 7s - loss: 2.415 - ETA: 7s - loss: 2.397 - ETA: 6s - loss: 2.383 - ETA: 6s - loss: 2.367 - ETA: 5s - loss: 2.350 - ETA: 4s - loss: 2.344 - ETA: 4s - loss: 2.343 - ETA: 3s - loss: 2.335 - ETA: 3s - loss: 2.331 - ETA: 3s - loss: 2.322 - ETA: 2s - loss: 2.312 - ETA: 2s - loss: 2.301 - ETA: 1s - loss: 2.286 - ETA: 1s - loss: 2.279 - ETA: 0s - loss: 2.267 - ETA: 0s - loss: 2.254 - ETA: 0s - loss: 2.248 - 12s 736us/step - loss: 2.2458 - val_loss: 1.8947
Epoch 2/10
16360/16360 [==============================] - ETA: 8s - loss: 1.943 - ETA: 8s - loss: 1.937 - ETA: 7s - loss: 1.924 - ETA: 7s - loss: 1.913 - ETA: 7s - loss: 1.931 - ETA: 7s - loss: 1

In [ ]:
# Saving the Model
model.save('Models/first_model')

In [ ]:
# Loading the Model
model.load('Models/first-model')

In [ ]:
#scores = []
#choices = []
env = CarRacing()
for each_game in range(3):
    #score = 0
    #game_memory = []
    prev_obs = env.reset()
    for i in range(1000):
        env.render()
        out = model.predict(prev_obs.reshape(-1,96,96,3))[0]
        print(out)
        
        if out[0]<=0.35:
            out[0]=0  
        if out[1]<=0.2:
            out[1]=0
        if out[2]<=0.01 :
            out[2]=0   
        if out[3]<=0.47:
            out[3]=0
        if out[4]<=9:
            out[4]=0    
        
        output = np.argmax(out)
        action = np.zeros(5)
        np.put(action, output, 1)
        #choices.append(action)
        if np.array_equal(action, np.array([0,0,1,0,0])):
            action=np.array([0,1,0])
        elif np.array_equal(action, np.array([0,0,0,1,0])):
            action=np.array([0,0,0.8])
        elif np.array_equal(action, np.array([0,1,0,0,0])):
            action=np.array([1,0,0])
        elif np.array_equal(action, np.array([1,0,0,0,0])):
            action=np.array([-1,0,0])
        else:
            action=np.array([0,0,0,0,0])
        
        new_observation, reward, done, info = env.step(action)
        print(action,"by nn")
        prev_obs = new_observation
        #game_memory.append([new_observation, action])
        #score+=reward
        if done: 
            break
    #scores.append(score)
    #print('Episode {} Score: {}'.format(each_game+1,score))
    env.close()
#print('Average Score:',sum(scores)/len(scores))

Track generation: 1053..1319 -> 266-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1176..1474 -> 298-tiles track
[1.6442436e-04 2.2818191e-05 2.5397397e-03 1.0105422e-06 9.9727196e-01]
[-1  0  0] by nn
[3.8031849e-01 1.8698987e-01 6.9211383e-05 1.6034690e-01 2.7227548e-01]
[-1  0  0] by nn
[3.0068852e-02 3.3695695e-01 1.6635846e-07 6.7396625e-03 6.2623435e-01]
[1 0 0] by nn
[2.8651420e-04 1.1327161e-01 2.7135920e-09 1.6442219e-03 8.8479763e-01]
[-1  0  0] by nn
[2.54116574e-04 1.00061744e-01 1.62610603e-09 2.22735573e-03
 8.97456765e-01]
[-1  0  0] by nn
[3.6044823e-04 4.5984864e-02 8.9258068e-10 2.6963069e-03 9.5095837e-01]
[-1  0  0] by nn
[8.1289635e-04 4.9936555e-02 3.7725627e-08 5.2610245e-03 9.4398952e-01]
[-1  0  0] by nn
[1.0201948e-01 2.6022905e-01 1.0197162e-05 1.6828600e-01 4.6945527e-01]
[1 0 0] by nn
[5.0902562e-03 1.1353251e-01 3.7955126e-06 1.8559307e-02 8.6281419e-01]
[-1  0  0] by nn
[4.1113165e-03 1.8662386e-01 3.

[-1  0  0] by nn
[0.7452909  0.01796904 0.0042201  0.14888923 0.08363084]
[-1  0  0] by nn
[0.7612344  0.01869725 0.00400068 0.15304963 0.06301811]
[-1  0  0] by nn
[0.80352277 0.01793198 0.00367551 0.13712482 0.03774488]
[-1  0  0] by nn
[0.8573612  0.0155085  0.00288463 0.10654648 0.01769911]
[-1  0  0] by nn
[0.9056179  0.01300782 0.00272077 0.06888136 0.00977216]
[-1  0  0] by nn
[0.9402388  0.01007068 0.00145702 0.04332605 0.00490751]
[-1  0  0] by nn
[0.9666936  0.00655877 0.00111908 0.02387036 0.00175826]
[-1  0  0] by nn
[9.8103720e-01 2.8731183e-03 4.4609801e-04 1.5084035e-02 5.5957068e-04]
[-1  0  0] by nn
[9.8790562e-01 1.3012532e-03 2.9170187e-04 1.0219314e-02 2.8218786e-04]
[-1  0  0] by nn
[9.8781002e-01 1.2273355e-03 3.3113893e-04 1.0313535e-02 3.1799887e-04]
[-1  0  0] by nn
[9.84027863e-01 1.62478583e-03 4.89942438e-04 1.30258165e-02
 8.31613492e-04]
[-1  0  0] by nn
[9.8669469e-01 1.5178721e-03 4.6838634e-04 1.0270450e-02 1.0484791e-03]
[-1  0  0] by nn
[9.8604298e-01

[0.0389013  0.68985456 0.01365943 0.12087542 0.13670924]
[1 0 0] by nn
[0.04117236 0.6348243  0.02382585 0.13142909 0.1687484 ]
[1 0 0] by nn
[0.04832905 0.52412605 0.05254585 0.13899897 0.23600005]
[1 0 0] by nn
[0.05365429 0.40098295 0.12995979 0.14549628 0.26990673]
[1 0 0] by nn
[0.06361601 0.26206425 0.22612877 0.14239404 0.30579698]
[1 0 0] by nn
[0.07692902 0.13606086 0.35474718 0.12708221 0.30518073]
[0 1 0] by nn
[0.12796156 0.08623727 0.3373322  0.11881502 0.32965395]
[0 1 0] by nn
[0.29053408 0.05824173 0.20066877 0.09655613 0.35399923]
[0 1 0] by nn
[0.5300423  0.02968962 0.06778339 0.0656932  0.3067915 ]
[-1  0  0] by nn
[0.73319054 0.01684641 0.0190362  0.04653165 0.18439524]
[-1  0  0] by nn
[0.8347407  0.00774704 0.00692507 0.0366597  0.11392753]
[-1  0  0] by nn
[0.8880217  0.00462702 0.0029029  0.03510603 0.06934225]
[-1  0  0] by nn
[0.8938496  0.00421762 0.00394662 0.03786587 0.06012021]
[-1  0  0] by nn
[0.934039   0.00265309 0.00133221 0.02655294 0.03542275]
[-1  

[0.13417777 0.07990909 0.34030828 0.10708246 0.3385224 ]
[0 1 0] by nn
[0.342109   0.05118238 0.18258736 0.08734462 0.33677667]
[0 1 0] by nn
[0.6395664  0.02148408 0.04609067 0.0561836  0.23667523]
[-1  0  0] by nn
[0.8019577  0.01238102 0.01287419 0.04012456 0.13266261]
[-1  0  0] by nn
[0.8548443  0.00782501 0.00632852 0.03521426 0.09578801]
[-1  0  0] by nn
[0.89389527 0.00550437 0.00327748 0.03292203 0.06440091]
[-1  0  0] by nn
[0.89022595 0.00472165 0.0045593  0.0421292  0.05836398]
[-1  0  0] by nn
[0.92285144 0.00311512 0.00165693 0.02960248 0.04277404]
[-1  0  0] by nn
[0.9205348  0.00275653 0.00169789 0.02670681 0.04830399]
[-1  0  0] by nn
[0.9248957  0.00390262 0.00153425 0.0222098  0.04745758]
[-1  0  0] by nn
[0.90907973 0.00504954 0.00242403 0.02492157 0.0585251 ]
[-1  0  0] by nn
[0.8949352  0.00627662 0.00376457 0.02886573 0.06615788]
[-1  0  0] by nn
[0.88847286 0.00952537 0.00607552 0.03361744 0.0623088 ]
[-1  0  0] by nn
[0.86684865 0.01355105 0.01158035 0.04030789

[0 1 0] by nn
[0.05264684 0.20728327 0.27345756 0.12175971 0.3448526 ]
[0 1 0] by nn
[0.03072377 0.35415804 0.2137003  0.09650207 0.30491582]
[1 0 0] by nn
[0.03192725 0.49528885 0.10980244 0.09952978 0.26345173]
[1 0 0] by nn
[0.02995251 0.5749111  0.07580132 0.10669854 0.21263653]
[1 0 0] by nn
[0.03380436 0.634439   0.04453749 0.11067929 0.17653991]
[1 0 0] by nn
[0.02917134 0.5943169  0.06710353 0.12079008 0.18861812]
[1 0 0] by nn
[0.03299725 0.64640397 0.04101891 0.10856068 0.17101914]
[1 0 0] by nn
[0.02834057 0.522897   0.07051419 0.11493229 0.26331592]
[1 0 0] by nn
[0.0344843  0.45721546 0.07821411 0.11374991 0.31633624]
[1 0 0] by nn
[0.03878265 0.31571326 0.12053327 0.10388977 0.42108104]
[1 0 0] by nn
[0.04237955 0.20297468 0.15864904 0.10262981 0.4933669 ]
[1 0 0] by nn
[0.05614707 0.15233608 0.16296606 0.10704174 0.52150905]
[0 1 0] by nn
[0.08309156 0.09015746 0.153811   0.09984136 0.5730986 ]
[0 1 0] by nn
[0.10905007 0.05779829 0.12325215 0.09621588 0.61368364]
[0 1 0

[9.9995983e-01 3.7255276e-07 3.4217629e-11 3.9855579e-05 4.5055789e-21]
[-1  0  0] by nn
[9.9998903e-01 3.6706176e-08 8.7572788e-13 1.0999590e-05 7.9353078e-26]
[-1  0  0] by nn
[9.9999523e-01 1.0818877e-08 5.6634385e-14 4.7516251e-06 2.4399622e-29]
[-1  0  0] by nn
[9.9999845e-01 1.5620881e-09 2.8795741e-15 1.5630860e-06 4.7763451e-33]
[-1  0  0] by nn
[9.9999940e-01 3.6638881e-10 3.9266745e-16 5.5298608e-07 2.3475299e-35]
[-1  0  0] by nn
[9.99999881e-01 1.17446969e-10 1.02141996e-16 1.74248342e-07
 3.92004927e-37]
[-1  0  0] by nn
[9.9999988e-01 1.3986733e-10 6.1823122e-17 1.2688702e-07 3.0779723e-38]
[-1  0  0] by nn
[9.9999988e-01 1.6642827e-10 6.5453095e-17 1.2055105e-07 4.0748515e-38]
[-1  0  0] by nn
[9.9999976e-01 1.2802233e-10 1.1138278e-16 2.2700920e-07 3.9760129e-37]
[-1  0  0] by nn
[9.9999964e-01 2.9883207e-10 3.0286449e-16 3.8833156e-07 9.1493301e-36]
[-1  0  0] by nn
[9.9999940e-01 9.9893871e-10 7.6999133e-16 6.2207471e-07 2.0279651e-33]
[-1  0  0] by nn
[9.9999797e-01 

[-1  0  0] by nn
[9.8532051e-01 5.4761823e-03 6.0647937e-05 9.1424081e-03 2.2634978e-07]
[-1  0  0] by nn
[9.9457645e-01 1.1870470e-03 4.3795467e-06 4.2320960e-03 2.1367983e-09]
[-1  0  0] by nn
[9.9698573e-01 4.4439311e-04 7.9857472e-07 2.5690515e-03 3.2697265e-11]
[-1  0  0] by nn
[9.7217870e-01 6.4835395e-03 1.2290666e-05 2.1325488e-02 3.0865905e-08]
[-1  0  0] by nn
[0.8622355  0.05318282 0.00660506 0.06700679 0.01096979]
[-1  0  0] by nn
[9.8906589e-01 3.0262596e-03 9.9411027e-06 7.8974031e-03 4.8494201e-07]
[-1  0  0] by nn
[9.7836405e-01 8.0750491e-03 2.1479643e-04 1.3343573e-02 2.5364245e-06]
[-1  0  0] by nn
[9.8260653e-01 5.4483982e-03 1.0337388e-04 1.1841022e-02 6.8966403e-07]
[-1  0  0] by nn
[9.8180652e-01 5.1398771e-03 1.4775757e-04 1.2904704e-02 1.2060484e-06]
[-1  0  0] by nn
[9.7976047e-01 6.5761250e-03 2.2503830e-04 1.3436664e-02 1.6974360e-06]
[-1  0  0] by nn
[9.7655475e-01 7.4656680e-03 2.5592407e-04 1.5721813e-02 1.8542903e-06]
[-1  0  0] by nn
[9.6680510e-01 1.18

[-1  0  0] by nn
[9.7589219e-01 6.0024858e-03 2.0088309e-04 1.7903337e-02 1.1371336e-06]
[-1  0  0] by nn
[9.7340834e-01 7.1354108e-03 2.7218071e-04 1.9182373e-02 1.7856892e-06]
[-1  0  0] by nn
[9.7351575e-01 7.5493157e-03 3.0872182e-04 1.8623896e-02 2.3427372e-06]
[-1  0  0] by nn
[9.7363836e-01 7.4877529e-03 3.4269926e-04 1.8528551e-02 2.6439589e-06]
[-1  0  0] by nn
[9.7577071e-01 7.1918182e-03 3.3539490e-04 1.6699368e-02 2.8089371e-06]
[-1  0  0] by nn
[9.7674632e-01 6.8729296e-03 3.1038973e-04 1.6067835e-02 2.5388390e-06]
[-1  0  0] by nn
[9.7664976e-01 6.7284345e-03 3.0396634e-04 1.6315298e-02 2.4402934e-06]
[-1  0  0] by nn
[9.7604126e-01 6.7582703e-03 3.2143155e-04 1.6876467e-02 2.5416950e-06]
[-1  0  0] by nn
[9.7616321e-01 6.8442477e-03 3.2863056e-04 1.6661344e-02 2.5036193e-06]
[-1  0  0] by nn
[9.7566128e-01 6.7128446e-03 3.5780453e-04 1.7265258e-02 2.7777119e-06]
[-1  0  0] by nn
[9.7488993e-01 6.7595141e-03 4.1292762e-04 1.7934578e-02 3.1887669e-06]
[-1  0  0] by nn
[9.7

[9.7771525e-01 6.2632905e-03 4.7322337e-05 1.5972564e-02 1.5686323e-06]
[-1  0  0] by nn
[9.8075908e-01 5.7433150e-03 4.0113806e-05 1.3456133e-02 1.2858925e-06]
[-1  0  0] by nn
[9.8392522e-01 4.9885395e-03 3.2033397e-05 1.1052999e-02 1.1897242e-06]
[-1  0  0] by nn
[9.8343062e-01 4.8464923e-03 2.9400564e-05 1.1692200e-02 1.3222314e-06]
[-1  0  0] by nn
[9.84773636e-01 4.52343933e-03 2.89144009e-05 1.06728235e-02
 1.20361483e-06]
[-1  0  0] by nn
[9.8470670e-01 5.0749085e-03 3.0026040e-05 1.0187156e-02 1.2159015e-06]
[-1  0  0] by nn
[9.8336625e-01 5.4773018e-03 3.7310558e-05 1.1117709e-02 1.4114913e-06]
[-1  0  0] by nn
[9.8193246e-01 5.8969208e-03 4.3956170e-05 1.2125177e-02 1.5102969e-06]
[-1  0  0] by nn
[9.8058677e-01 6.4134044e-03 5.3749805e-05 1.2944177e-02 1.8579076e-06]
[-1  0  0] by nn
[9.8118997e-01 6.4377682e-03 7.2732073e-05 1.2297293e-02 2.2043509e-06]
[-1  0  0] by nn
[9.8104459e-01 6.3229399e-03 1.2310360e-04 1.2506272e-02 3.0485839e-06]
[-1  0  0] by nn
[9.7981757e-01 

[-1  0  0] by nn
[9.6694171e-01 8.5664485e-03 5.3455000e-04 2.3949666e-02 7.6900205e-06]
[-1  0  0] by nn
[9.6818817e-01 8.3868252e-03 5.3999468e-04 2.2876943e-02 8.0539148e-06]
[-1  0  0] by nn
[9.6937156e-01 8.2472516e-03 5.5894483e-04 2.1814084e-02 8.0321679e-06]
[-1  0  0] by nn
[9.6887892e-01 8.3512664e-03 5.8989559e-04 2.2171747e-02 8.0388127e-06]
[-1  0  0] by nn
[9.6878290e-01 8.5571790e-03 5.7587400e-04 2.2075284e-02 8.7538047e-06]
[-1  0  0] by nn
[9.6783900e-01 8.6477194e-03 5.5222108e-04 2.2951934e-02 9.1229203e-06]
[-1  0  0] by nn
[9.688297e-01 8.440166e-03 5.314799e-04 2.218991e-02 8.827230e-06]
[-1  0  0] by nn
[9.6845722e-01 8.3506536e-03 5.1615667e-04 2.2667272e-02 8.6080399e-06]
[-1  0  0] by nn
[9.7212481e-01 8.3801951e-03 4.7075073e-04 1.9017247e-02 6.9885523e-06]
[-1  0  0] by nn
[9.7324717e-01 8.0153458e-03 4.4145217e-04 1.8289598e-02 6.3800658e-06]
[-1  0  0] by nn
[9.7448593e-01 7.5420151e-03 4.2651212e-04 1.7539676e-02 5.9192448e-06]
[-1  0  0] by nn
[9.749778

[-1  0  0] by nn
[0.39261335 0.13998263 0.13835344 0.19632618 0.1327244 ]
[-1  0  0] by nn
[0.3746612  0.13906693 0.14074662 0.19988264 0.14564261]
[-1  0  0] by nn
[0.36464864 0.13368149 0.1437171  0.20129415 0.1566585 ]
[-1  0  0] by nn
[0.35635972 0.1337042  0.14450072 0.19801508 0.16742024]
[-1  0  0] by nn
[0.37840202 0.12037431 0.13599251 0.17436701 0.19086406]
[-1  0  0] by nn
[0.36266455 0.1230021  0.14053908 0.17727335 0.19652101]
[-1  0  0] by nn
[0.3434517  0.12478846 0.14088693 0.18642372 0.20444918]
[0 1 0] by nn
[0.23557395 0.1384845  0.28141555 0.18164651 0.16287948]
[0 1 0] by nn
[0.18956132 0.13674794 0.30774996 0.16303219 0.20290862]
[0 1 0] by nn
[0.13500912 0.1716199  0.28929153 0.17294152 0.23113793]
[0 1 0] by nn
[0.12188192 0.1909545  0.28545725 0.16152094 0.24018538]
[0 1 0] by nn
[0.11201273 0.17499422 0.28782234 0.17239118 0.2527795 ]
[0 1 0] by nn
[0.11525576 0.17648351 0.26550487 0.17015114 0.27260473]
[0 1 0] by nn
[0.07501296 0.13540635 0.39930204 0.149136

[0.87503445 0.00447165 0.00217201 0.02078556 0.09753635]
[-1  0  0] by nn
[0.8399708  0.00578437 0.00299482 0.0246957  0.12655431]
[-1  0  0] by nn
[0.83675903 0.00900638 0.00388874 0.02854298 0.12180282]
[-1  0  0] by nn
[0.8189613  0.01202316 0.0053858  0.03463705 0.12899272]
[-1  0  0] by nn
[0.76199347 0.01455954 0.0076752  0.03947945 0.17629224]
[-1  0  0] by nn
[0.62988985 0.02949548 0.01897853 0.06028523 0.26135093]
[-1  0  0] by nn
[0.47305837 0.05025521 0.03548867 0.0853299  0.35586786]
[-1  0  0] by nn
[0.29275352 0.08256714 0.06648082 0.11196116 0.4462374 ]
[0 1 0] by nn
[0.13482974 0.14020184 0.09194615 0.12286248 0.5101598 ]
[0 1 0] by nn
[0.05951812 0.19287637 0.08564321 0.09660957 0.56535274]
[0 1 0] by nn
[0.03612828 0.32569563 0.05552935 0.08330695 0.49933973]
[1 0 0] by nn
[0.03524543 0.44232705 0.0314355  0.07351087 0.41748115]
[1 0 0] by nn
[0.03296225 0.53519946 0.01830938 0.09422069 0.31930822]
[1 0 0] by nn
[0.04859082 0.5377465  0.0141027  0.11413709 0.28542295]

[-1  0  0] by nn
[9.9615341e-01 7.4751803e-04 6.6203427e-07 3.0983847e-03 2.5521609e-14]
[-1  0  0] by nn
[9.9582016e-01 7.6946866e-04 8.2854837e-07 3.4094837e-03 3.3403581e-14]
[-1  0  0] by nn
[9.9664813e-01 6.6956499e-04 5.8429930e-07 2.6817091e-03 2.3850967e-14]
[-1  0  0] by nn
[9.9666959e-01 6.9527002e-04 7.2711578e-07 2.6344489e-03 4.1480108e-14]
[-1  0  0] by nn
[9.9672014e-01 6.8250654e-04 7.3954743e-07 2.5966489e-03 5.8611651e-14]
[-1  0  0] by nn
[9.9662220e-01 6.1132823e-04 6.9533769e-07 2.7657573e-03 5.0560379e-14]
[-1  0  0] by nn
[9.9664551e-01 6.2541675e-04 8.0541258e-07 2.7282757e-03 8.6417899e-14]
[-1  0  0] by nn
[9.9640590e-01 6.1765453e-04 9.3771359e-07 2.9754885e-03 1.1243919e-13]
[-1  0  0] by nn
[9.9586630e-01 7.8021316e-04 1.6295539e-06 3.3518537e-03 3.3031333e-13]
[-1  0  0] by nn
[9.9563342e-01 7.2587241e-04 1.7902677e-06 3.6389260e-03 1.0370872e-12]
[-1  0  0] by nn
[9.9505568e-01 7.8407448e-04 1.5828847e-06 4.1586794e-03 1.1050726e-12]
[-1  0  0] by nn
[9.9

[0.70026094 0.01591328 0.05223329 0.08086244 0.15073006]
[-1  0  0] by nn
[0.6832019  0.0180888  0.05764682 0.08866293 0.15239951]
[-1  0  0] by nn
[0.67253613 0.01844151 0.06376226 0.08782362 0.15743643]
[-1  0  0] by nn
[0.6701946  0.01918608 0.06523507 0.08461905 0.16076514]
[-1  0  0] by nn
[0.6554241  0.02124629 0.0724818  0.08933072 0.16151707]
[-1  0  0] by nn
[0.6339806  0.02393712 0.08343795 0.0929485  0.1656958 ]
[-1  0  0] by nn
[0.61543787 0.0252984  0.09164187 0.09544204 0.17217988]
[-1  0  0] by nn
[0.6104157  0.02580193 0.09642798 0.09299731 0.17435706]
[-1  0  0] by nn
[0.5949049  0.02624942 0.10594425 0.09269866 0.18020274]
[-1  0  0] by nn
[0.58347166 0.02875195 0.11161447 0.09277059 0.18339132]
[-1  0  0] by nn
[0.57334965 0.03168084 0.11391138 0.09768984 0.18336831]
[-1  0  0] by nn
[0.5520834  0.03293172 0.13336131 0.09433083 0.18729275]
[-1  0  0] by nn
[0.538594   0.03555906 0.14052092 0.09611171 0.18921429]
[-1  0  0] by nn
[0.5180903  0.03639777 0.16086139 0.09

[0.07877319 0.11064582 0.40593547 0.1360337  0.26861185]
[0 1 0] by nn
[0.07542564 0.11142697 0.413865   0.13210887 0.26717347]
[0 1 0] by nn
[0.07439024 0.11384027 0.4105733  0.13283837 0.2683578 ]
[0 1 0] by nn
[0.07043623 0.1104482  0.4348966  0.13232115 0.25189787]
[0 1 0] by nn
[0.07087842 0.11108278 0.43769926 0.13228068 0.24805883]
[0 1 0] by nn
[0.07278157 0.10938399 0.4230403  0.13339995 0.26139417]
[0 1 0] by nn
[0.07486078 0.11647838 0.41658935 0.13751431 0.25455716]
[0 1 0] by nn
[0.07620603 0.1178507  0.41917026 0.1385287  0.24824432]
[0 1 0] by nn
[0.0754143  0.10893117 0.44320586 0.13812363 0.234325  ]
[0 1 0] by nn
[0.07724142 0.10981517 0.438917   0.14147401 0.23255248]
[0 1 0] by nn
[0.07612219 0.10476302 0.45906714 0.14003028 0.22001734]
[0 1 0] by nn
[0.07822364 0.10367728 0.45888215 0.14120989 0.21800701]
[0 1 0] by nn
[0.09516703 0.11615591 0.41254166 0.15854414 0.21759127]
[0 1 0] by nn
[0.09603163 0.11729398 0.40606412 0.15886971 0.22174051]
[0 1 0] by nn
[0.096

[1.6994862e-01 3.0183023e-01 5.8862166e-05 3.0981317e-01 2.1834916e-01]
[1 0 0] by nn
[9.0116426e-02 2.2733979e-01 1.3491916e-04 5.2864742e-01 1.5376149e-01]
[0.  0.  0.8] by nn
[2.9946480e-02 1.7814164e-01 1.9408121e-04 6.0065335e-01 1.9106445e-01]
[0.  0.  0.8] by nn
[2.10733116e-02 1.58425197e-01 2.77707819e-04 7.09935784e-01
 1.10288106e-01]
[0.  0.  0.8] by nn
[3.1013114e-02 2.7401546e-01 2.2344930e-04 6.0849136e-01 8.6256661e-02]
[0.  0.  0.8] by nn
[0.05776582 0.3870489  0.00066305 0.529055   0.02546729]
[0.  0.  0.8] by nn
[0.1033816  0.5308863  0.00115529 0.35733035 0.00724647]
[1 0 0] by nn
[0.02912885 0.50771224 0.01023024 0.44399136 0.0089373 ]
[1 0 0] by nn
[0.17853566 0.47753695 0.01128545 0.3318825  0.00075945]
[1 0 0] by nn
[4.2635447e-01 1.7462753e-01 6.0479164e-02 3.3834749e-01 1.9132587e-04]
[-1  0  0] by nn
[6.7692244e-01 6.8244606e-02 6.5307960e-02 1.8943998e-01 8.4987398e-05]
[-1  0  0] by nn
[5.46569824e-01 5.41860610e-02 2.91180640e-01 1.07573055e-01
 4.90507402

[-1  0  0] by nn
[9.9997663e-01 2.8549675e-07 5.9253309e-09 2.3087337e-05 4.4946532e-20]
[-1  0  0] by nn
[9.9999094e-01 9.3841621e-08 1.3863352e-09 8.9783916e-06 3.2236179e-22]
[-1  0  0] by nn
[9.9999678e-01 2.0633586e-08 2.4947622e-10 3.1601210e-06 5.9589389e-25]
[-1  0  0] by nn
[9.9999905e-01 5.6577090e-09 3.4666870e-11 9.7438499e-07 2.0611485e-27]
[-1  0  0] by nn
[9.9999976e-01 9.3630859e-10 3.6060640e-12 2.4865170e-07 3.0852021e-30]
[-1  0  0] by nn
[9.9999988e-01 2.1391834e-10 2.4493799e-13 1.1849592e-07 6.7241326e-33]
[-1  0  0] by nn
[9.9999988e-01 1.3165133e-10 3.1658222e-14 8.2343163e-08 1.4211594e-33]
[-1  0  0] by nn
[1.0000000e+00 5.1244821e-11 2.9303641e-15 3.2962042e-08 2.5060199e-33]
[-1  0  0] by nn
[1.0000000e+00 3.0587732e-10 4.7792945e-15 5.2501278e-08 5.7090544e-31]
[-1  0  0] by nn
[9.9999988e-01 2.7705291e-09 1.1587116e-14 1.0410183e-07 1.7320983e-26]
[-1  0  0] by nn
[9.9999917e-01 6.3494284e-08 1.0817861e-13 6.8275546e-07 9.4761193e-22]
[-1  0  0] by nn
[9.9

[0.23209542 0.10985405 0.380142   0.13495834 0.14295012]
[0 1 0] by nn
[0.1341525  0.16233763 0.41278782 0.14315547 0.14756654]
[0 1 0] by nn
[0.10230454 0.2777267  0.3067834  0.1582311  0.15495428]
[0 1 0] by nn
[0.08853084 0.49825227 0.1289497  0.14367084 0.1405964 ]
[1 0 0] by nn
[0.07311237 0.65327495 0.0457896  0.1326615  0.09516156]
[1 0 0] by nn
[0.06917083 0.70768875 0.01702431 0.13512152 0.07099457]
[1 0 0] by nn
[0.08927629 0.70208305 0.0086902  0.14191616 0.05803444]
[1 0 0] by nn
[0.05150837 0.7306382  0.01328057 0.14724249 0.05733038]
[1 0 0] by nn
[0.06654619 0.73481363 0.00682565 0.1323178  0.05949675]
[1 0 0] by nn
[0.06416997 0.7059733  0.00941429 0.14655927 0.07388316]
[1 0 0] by nn
[0.06923912 0.7228552  0.00865422 0.13077773 0.06847367]
[1 0 0] by nn
[0.07126497 0.67879313 0.01226201 0.13800862 0.09967131]
[1 0 0] by nn
[0.07024076 0.65313345 0.01991878 0.14792049 0.10878652]
[1 0 0] by nn
[0.06742587 0.6092429  0.0500958  0.14526983 0.12796555]
[1 0 0] by nn
[0.066

[-1  0  0] by nn
[0.31044868 0.11978677 0.14896238 0.1944969  0.22630532]
[0 1 0] by nn
[0.12896492 0.2387141  0.14321245 0.20388182 0.28522667]
[1 0 0] by nn
[0.05975938 0.3574286  0.10605597 0.14469013 0.33206594]
[1 0 0] by nn
[0.03523781 0.55334175 0.05947943 0.10176298 0.25017795]
[1 0 0] by nn
[0.0223077  0.7429274  0.02225249 0.07129809 0.14121425]
[1 0 0] by nn
[0.03822134 0.7521024  0.01106647 0.06266131 0.13594846]
[1 0 0] by nn
[0.04627267 0.76304716 0.00570192 0.07020482 0.11477335]
[1 0 0] by nn
[0.02577713 0.7819846  0.00677659 0.07587937 0.10958222]
[1 0 0] by nn
[0.02910535 0.8216457  0.0018643  0.05711469 0.09026992]
[1 0 0] by nn
[0.02630842 0.7737097  0.00302099 0.08282836 0.11413242]
[1 0 0] by nn
[0.0237001  0.809553   0.00160299 0.05950365 0.10564019]
[1 0 0] by nn
[0.03187063 0.7439685  0.00308079 0.07339228 0.1476878 ]
[1 0 0] by nn
[0.03235515 0.71647793 0.00731656 0.0691604  0.17469001]
[1 0 0] by nn
[0.02438431 0.7366755  0.01104641 0.06684449 0.16104922]
[1 

[0.3445285  0.05576985 0.02059003 0.317639   0.26147264]
[0 1 0] by nn
[0.41652593 0.04659536 0.01450883 0.3474675  0.17490242]
[-1  0  0] by nn
[0.63657844 0.02814309 0.00512953 0.23580307 0.09434579]
[-1  0  0] by nn
[0.68175584 0.02346501 0.00410716 0.22174145 0.06893063]
[-1  0  0] by nn
[0.73751116 0.02499432 0.00480048 0.17377004 0.058924  ]
[-1  0  0] by nn
[0.7644842  0.02319626 0.00454892 0.1634198  0.04435078]
[-1  0  0] by nn
[0.79561794 0.01942474 0.0045453  0.14559908 0.03481295]
[-1  0  0] by nn
[0.86668295 0.01449732 0.00318268 0.09638847 0.01924863]
[-1  0  0] by nn
[0.888553   0.01447992 0.0034092  0.07826041 0.01529755]
[-1  0  0] by nn
[0.9001325  0.01316461 0.00385841 0.06812647 0.01471804]
[-1  0  0] by nn
[0.92345023 0.0121526  0.0037932  0.04927615 0.01132779]
[-1  0  0] by nn
[0.9298946  0.01317514 0.00448198 0.0434419  0.00900642]
[-1  0  0] by nn
[0.95144486 0.00630959 0.00270221 0.03260785 0.00693544]
[-1  0  0] by nn
[0.93455505 0.00783923 0.00390687 0.04151

[0.04389786 0.23763119 0.27611604 0.15190183 0.29045308]
[0 1 0] by nn
[0.04298206 0.24712558 0.26899317 0.14875023 0.29214895]
[0 1 0] by nn
[0.04300766 0.25814846 0.26223704 0.14860396 0.28800288]
[0 1 0] by nn
[0.04101745 0.2688709  0.27094224 0.14855285 0.2706165 ]
[0 1 0] by nn
[0.04159296 0.27826345 0.27241877 0.14887868 0.25884616]
[1 0 0] by nn
[0.05165308 0.36859578 0.16828689 0.15518543 0.25627878]
[1 0 0] by nn
[0.06161404 0.28076953 0.19344011 0.15113713 0.3130392 ]
[1 0 0] by nn
[0.07320479 0.22877513 0.24569902 0.14800261 0.30431846]
[0 1 0] by nn
[0.09031578 0.14194311 0.3443552  0.13927431 0.28411162]
[0 1 0] by nn
[0.12629002 0.12737589 0.3392396  0.14179818 0.26529637]
[0 1 0] by nn
[0.10903624 0.07573213 0.48082182 0.12275696 0.21165287]
[0 1 0] by nn
[0.12712714 0.07581781 0.4708072  0.13021718 0.1960307 ]
[0 1 0] by nn
[0.16719441 0.06510473 0.43922836 0.13196275 0.19650978]
[0 1 0] by nn
[0.22198908 0.05859832 0.40446058 0.13148075 0.18347123]
[0 1 0] by nn
[0.283

[9.9998271e-01 4.1273640e-07 2.1736954e-10 1.6986163e-05 1.1282681e-22]
[-1  0  0] by nn
[9.9998784e-01 2.1697500e-07 7.5710764e-11 1.1943161e-05 1.3044486e-23]
[-1  0  0] by nn
[9.99992847e-01 1.11344505e-07 2.41548795e-11 7.08487551e-06
 1.43152123e-24]
[-1  0  0] by nn
[9.9999404e-01 8.4300360e-08 8.8744082e-12 5.8087453e-06 6.1053318e-25]
[-1  0  0] by nn
[9.99992967e-01 1.07365494e-07 7.02927083e-12 6.93806305e-06
 5.88661763e-25]
[-1  0  0] by nn
[9.9999332e-01 1.4218726e-07 8.0630684e-12 6.6021958e-06 2.7279950e-24]
[-1  0  0] by nn
[9.9998021e-01 6.2447543e-07 4.1978546e-11 1.9193683e-05 8.9765010e-22]
[-1  0  0] by nn
[9.9997187e-01 1.3223843e-06 3.3091038e-10 2.6877655e-05 1.1985976e-20]
[-1  0  0] by nn
[9.9994767e-01 4.3373975e-06 1.2647555e-09 4.8064470e-05 4.0118928e-17]
[-1  0  0] by nn
[9.9981886e-01 1.4376774e-05 3.7156960e-09 1.6670805e-04 3.3703417e-14]
[-1  0  0] by nn
[9.9956197e-01 3.1318934e-05 2.3383590e-08 4.0667993e-04 4.8655083e-11]
[-1  0  0] by nn
[9.987835

[3.6697529e-04 9.9163693e-01 1.5340903e-07 2.4675119e-03 5.5284700e-03]
[1 0 0] by nn
[5.2119500e-04 9.8915720e-01 3.8829370e-07 4.8620366e-03 5.4591498e-03]
[1 0 0] by nn
[7.3324831e-04 9.8294765e-01 8.4546724e-07 8.1356782e-03 8.1825480e-03]
[1 0 0] by nn
[1.9137359e-03 9.7644436e-01 9.9051169e-07 7.1960120e-03 1.4444983e-02]
[1 0 0] by nn
[3.0595541e-03 9.7080392e-01 1.8813313e-06 8.1201475e-03 1.8014461e-02]
[1 0 0] by nn
[2.5074931e-03 9.7340333e-01 2.4048184e-06 7.8162998e-03 1.6270474e-02]
[1 0 0] by nn
[2.4289305e-03 9.7029489e-01 7.7685072e-06 1.0166155e-02 1.7102247e-02]
[1 0 0] by nn
[3.0531292e-03 9.6147424e-01 4.9568305e-05 1.7717006e-02 1.7705936e-02]
[1 0 0] by nn
[3.2761146e-03 9.4318330e-01 3.3984412e-04 3.1323839e-02 2.1876788e-02]
[1 0 0] by nn
[0.00722855 0.8914196  0.00315716 0.07351442 0.02468014]
[1 0 0] by nn
[0.00744721 0.83610964 0.01406579 0.11627074 0.02610662]
[1 0 0] by nn
[0.00803021 0.7552996  0.05478101 0.15817435 0.02371487]
[1 0 0] by nn
[0.01168185 0

[5.8560451e-03 9.7470349e-01 5.4593349e-04 1.8393317e-02 5.0128903e-04]
[1 0 0] by nn
[4.3558269e-03 9.7887623e-01 2.2687388e-04 1.5790202e-02 7.5092987e-04]
[1 0 0] by nn
[4.7327308e-03 9.6697491e-01 2.9146831e-04 2.5810670e-02 2.1901985e-03]
[1 0 0] by nn
[7.6304469e-03 9.5699579e-01 5.1272725e-04 2.7798897e-02 7.0621730e-03]
[1 0 0] by nn
[0.00703398 0.9497998  0.00121542 0.03012239 0.01182836]
[1 0 0] by nn
[0.02382325 0.8646669  0.00814087 0.07353824 0.0298308 ]
[1 0 0] by nn
[0.02844156 0.79384977 0.03052283 0.09872183 0.04846405]
[1 0 0] by nn
[0.03468559 0.706579   0.06266429 0.10398234 0.09208877]
[1 0 0] by nn
[0.05648088 0.55380964 0.10970686 0.11979787 0.16020475]
[1 0 0] by nn
[0.05762383 0.38821942 0.25938106 0.1130961  0.18167958]
[1 0 0] by nn
[0.06727998 0.19689544 0.45547685 0.10689315 0.17345458]
[0 1 0] by nn
[0.08926301 0.0836753  0.5785997  0.0918247  0.15663731]
[0 1 0] by nn
[0.19767627 0.04034716 0.5321174  0.07909561 0.1507636 ]
[0 1 0] by nn
[0.4448488  0.023